/*----- PROTECTED REGION ID(Layout.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        Layout.cpp
//
// description : C++ source for the Layout class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               Layout are implemented in this file.
//
// project :     Lima Layout Device Specific
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <Layout.h>
#include <LayoutClass.h>

/*----- PROTECTED REGION END -----*/	//	Layout.cpp

/**
 *  Layout class description:
 *    Lima Device Specific for post process image
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name     |  Method name
//================================================================
//  State            |  Inherited (no method)
//  Status           |  Inherited (no method)
//  AddOperation     |  add_operation
//  RemoveOperation  |  remove_operation
//================================================================

//================================================================
//  Attributes managed are:
//================================================================
//  version         |  Tango::DevString	Scalar
//  operationType   |  Tango::DevString	Scalar
//  operationValue  |  Tango::DevString	Scalar
//  operationsList  |  Tango::DevString	Spectrum  ( max = 1024)
//================================================================

namespace Layout_ns
{
/*----- PROTECTED REGION ID(Layout::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	Layout::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : Layout::Layout()
 *	Description : Constructors for a Tango device
 *                implementing the classLayout
 */
//--------------------------------------------------------
Layout::Layout(Tango::DeviceClass *cl, string &s)
 : Tango::Device_4Impl(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(Layout::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	Layout::constructor_1
}
//--------------------------------------------------------
Layout::Layout(Tango::DeviceClass *cl, const char *s)
 : Tango::Device_4Impl(cl, s)
{
	/*----- PROTECTED REGION ID(Layout::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	Layout::constructor_2
}
//--------------------------------------------------------
Layout::Layout(Tango::DeviceClass *cl, const char *s, const char *d)
 : Tango::Device_4Impl(cl, s, d)
{
	/*----- PROTECTED REGION ID(Layout::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	Layout::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : Layout::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void Layout::delete_device()
{
	DEBUG_STREAM << "Layout::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(Layout::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	
	/*----- PROTECTED REGION END -----*/	//	Layout::delete_device
}

//--------------------------------------------------------
/**
 *	Method      : Layout::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void Layout::init_device()
{
	DEBUG_STREAM << "Layout::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(Layout::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	Layout::init_device_before
	

	//	Get the device properties from database
	get_device_property();
	

	/*----- PROTECTED REGION ID(Layout::init_device) ENABLED START -----*/
	
	//	Initialize device
	
	/*----- PROTECTED REGION END -----*/	//	Layout::init_device
}

//--------------------------------------------------------
/**
 *	Method      : Layout::get_device_property()
 *	Description : Read database to initialize property data members.
 */
//--------------------------------------------------------
void Layout::get_device_property()
{
	/*----- PROTECTED REGION ID(Layout::get_device_property_before) ENABLED START -----*/
	
	//	Initialize property data members
	
	/*----- PROTECTED REGION END -----*/	//	Layout::get_device_property_before


	//	Read device properties from database.
	Tango::DbData	dev_prop;
	dev_prop.push_back(Tango::DbDatum("MemorizedOperationTypes"));
	dev_prop.push_back(Tango::DbDatum("MemorizedOperationValues"));
	dev_prop.push_back(Tango::DbDatum("MemorizedOperationLevels"));

	//	is there at least one property to be read ?
	if (dev_prop.size()>0)
	{
		//	Call database and extract values
		if (Tango::Util::instance()->_UseDb==true)
			get_db_device()->get_property(dev_prop);
	
		//	get instance on LayoutClass to get class property
		Tango::DbDatum	def_prop, cl_prop;
		LayoutClass	*ds_class =
			(static_cast<LayoutClass *>(get_device_class()));
		int	i = -1;

		//	Try to initialize MemorizedOperationTypes from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  memorizedOperationTypes;
		else {
			//	Try to initialize MemorizedOperationTypes from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  memorizedOperationTypes;
		}
		//	And try to extract MemorizedOperationTypes value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  memorizedOperationTypes;

		//	Try to initialize MemorizedOperationValues from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  memorizedOperationValues;
		else {
			//	Try to initialize MemorizedOperationValues from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  memorizedOperationValues;
		}
		//	And try to extract MemorizedOperationValues value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  memorizedOperationValues;

		//	Try to initialize MemorizedOperationLevels from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  memorizedOperationLevels;
		else {
			//	Try to initialize MemorizedOperationLevels from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  memorizedOperationLevels;
		}
		//	And try to extract MemorizedOperationLevels value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  memorizedOperationLevels;

	}

	/*----- PROTECTED REGION ID(Layout::get_device_property_after) ENABLED START -----*/
	
	//	Check device property data members init
	
	/*----- PROTECTED REGION END -----*/	//	Layout::get_device_property_after
}

//--------------------------------------------------------
/**
 *	Method      : Layout::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void Layout::always_executed_hook()
{
	INFO_STREAM << "Layout::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(Layout::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	Layout::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : Layout::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void Layout::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "Layout::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(Layout::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Layout::read_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute version related method
 *	Description: Display the Version of the Layout Device
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Layout::read_version(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Layout::read_version(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Layout::read_version) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_version_read);
	
	/*----- PROTECTED REGION END -----*/	//	Layout::read_version
}
//--------------------------------------------------------
/**
 *	Read attribute operationType related method
 *	Description: Arithmetic available types :<br>\n+ <br>\n- <br>\n* <br>\n/ <br>\n>> <br>\n<< <br>\nFLIP<br>\nROTATION<br>\nCIRPAD_2X10<br>\nCIRPAD_4X5<br>\nNONE <br>
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Layout::read_operationType(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Layout::read_operationType(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Layout::read_operationType) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_operationType_read);
	
	/*----- PROTECTED REGION END -----*/	//	Layout::read_operationType
}
//--------------------------------------------------------
/**
 *	Write attribute operationType related method
 *	Description: Arithmetic available types :<br>\n+ <br>\n- <br>\n* <br>\n/ <br>\n>> <br>\n<< <br>\nFLIP<br>\nROTATION<br>\nCIRPAD_2X10<br>\nCIRPAD_4X5<br>\nNONE <br>
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Layout::write_operationType(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "Layout::write_operationType(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevString	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(Layout::write_operationType) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	Layout::write_operationType
}
//--------------------------------------------------------
/**
 *	Read attribute operationValue related method
 *	Description: Arithmetic available values :<br>\nany numeric value\n\nFlip available values :<br>\nX<br>\nY<br>\nXY<br>\n\nRotation available values :<br>\n90<br>\n180<br>\n270<br>\n
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Layout::read_operationValue(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Layout::read_operationValue(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Layout::read_operationValue) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_operationValue_read);
	
	/*----- PROTECTED REGION END -----*/	//	Layout::read_operationValue
}
//--------------------------------------------------------
/**
 *	Write attribute operationValue related method
 *	Description: Arithmetic available values :<br>\nany numeric value\n\nFlip available values :<br>\nX<br>\nY<br>\nXY<br>\n\nRotation available values :<br>\n90<br>\n180<br>\n270<br>\n
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Layout::write_operationValue(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "Layout::write_operationValue(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevString	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(Layout::write_operationValue) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	Layout::write_operationValue
}
//--------------------------------------------------------
/**
 *	Read attribute operationsList related method
 *	Description: Enumerate all Layout active 'post processing' operations on the image.
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Spectrum max = 1024
 */
//--------------------------------------------------------
void Layout::read_operationsList(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Layout::read_operationsList(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Layout::read_operationsList) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_operationsList_read, 1024);
	
	/*----- PROTECTED REGION END -----*/	//	Layout::read_operationsList
}

//--------------------------------------------------------
/**
 *	Method      : Layout::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void Layout::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(Layout::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	Layout::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Command AddOperation related method
 *	Description: Add Lima external operation in order to transform the image acquired from the detector.<br>
 *               User must first define the operationType, operationValue attributes<br>
 *               argin will define the level of operation.
 *
 *	@param argin 
 */
//--------------------------------------------------------
void Layout::add_operation(Tango::DevLong argin)
{
	DEBUG_STREAM << "Layout::AddOperation()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(Layout::add_operation) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Layout::add_operation
}
//--------------------------------------------------------
/**
 *	Command RemoveOperation related method
 *	Description: Remove a Lima external operation previously defined at the the level = argin.<br>
 *
 *	@param argin 
 */
//--------------------------------------------------------
void Layout::remove_operation(Tango::DevLong argin)
{
	DEBUG_STREAM << "Layout::RemoveOperation()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(Layout::remove_operation) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Layout::remove_operation
}

/*----- PROTECTED REGION ID(Layout::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	Layout::namespace_ending
} //	namespace
