/*----- PROTECTED REGION ID(Layout.h) ENABLED START -----*/
//=============================================================================
//
// file :        Layout.h
//
// description : Include file for the Layout class
//
// project :     Lima Layout Device Specific
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef Layout_H
#define Layout_H

#include <tango.h>


/*----- PROTECTED REGION END -----*/	//	Layout.h

/**
 *  Layout class description:
 *    Lima Device Specific for post process image
 */

namespace Layout_ns
{
/*----- PROTECTED REGION ID(Layout::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	Layout::Additional Class Declarations

class Layout : public Tango::Device_4Impl
{

/*----- PROTECTED REGION ID(Layout::Data Members) ENABLED START -----*/

//	Add your own data members

/*----- PROTECTED REGION END -----*/	//	Layout::Data Members

//	Device property data members
public:
	//	MemorizedOperationTypes:	Memorize all operationType declared in the order to process the image.
	vector<string>	memorizedOperationTypes;
	//	MemorizedOperationValues:	Memorize all operationValue associated to the operationType declared in the order to process the image.
	vector<string>	memorizedOperationValues;
	//	MemorizedOperationLevels:	Memorize all levels associated to the operationType declared in the order to process the image.
	vector<Tango::DevLong>	memorizedOperationLevels;

//	Attribute data members
public:
	Tango::DevString	*attr_version_read;
	Tango::DevString	*attr_operationType_read;
	Tango::DevString	*attr_operationValue_read;
	Tango::DevString	*attr_operationsList_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	Layout(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	Layout(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	Layout(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */	
	~Layout() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : Layout::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute version related methods
 *	Description: Display the Version of the Layout Device
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_version(Tango::Attribute &attr);
	virtual bool is_version_allowed(Tango::AttReqType type);
/**
 *	Attribute operationType related methods
 *	Description: Arithmetic available types :<br>\n+ <br>\n- <br>\n* <br>\n/ <br>\n>> <br>\n<< <br>\nFLIP<br>\nROTATION<br>\nCIRPAD_2X10<br>\nCIRPAD_4X5<br>\nNONE <br>
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_operationType(Tango::Attribute &attr);
	virtual void write_operationType(Tango::WAttribute &attr);
	virtual bool is_operationType_allowed(Tango::AttReqType type);
/**
 *	Attribute operationValue related methods
 *	Description: Arithmetic available values :<br>\nany numeric value\n\nFlip available values :<br>\nX<br>\nY<br>\nXY<br>\n\nRotation available values :<br>\n90<br>\n180<br>\n270<br>\n
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_operationValue(Tango::Attribute &attr);
	virtual void write_operationValue(Tango::WAttribute &attr);
	virtual bool is_operationValue_allowed(Tango::AttReqType type);
/**
 *	Attribute operationsList related methods
 *	Description: Enumerate all Layout active 'post processing' operations on the image.
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Spectrum max = 1024
 */
	virtual void read_operationsList(Tango::Attribute &attr);
	virtual bool is_operationsList_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : Layout::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();



//	Command related methods
public:
	/**
	 *	Command AddOperation related method
	 *	Description: Add Lima external operation in order to transform the image acquired from the detector.<br>
	 *               User must first define the operationType, operationValue attributes<br>
	 *               argin will define the level of operation.
	 *
	 *	@param argin 
	 */
	virtual void add_operation(Tango::DevLong argin);
	virtual bool is_AddOperation_allowed(const CORBA::Any &any);
	/**
	 *	Command RemoveOperation related method
	 *	Description: Remove a Lima external operation previously defined at the the level = argin.<br>
	 *
	 *	@param argin 
	 */
	virtual void remove_operation(Tango::DevLong argin);
	virtual bool is_RemoveOperation_allowed(const CORBA::Any &any);


/*----- PROTECTED REGION ID(Layout::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes

/*----- PROTECTED REGION END -----*/	//	Layout::Additional Method prototypes
};

/*----- PROTECTED REGION ID(Layout::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	Layout::Additional Classes Definitions

}	//	End of namespace

#endif   //	Layout_H
