/*----- PROTECTED REGION ID(FitGaussian.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        FitGaussian.cpp
//
// description : C++ source for the FitGaussian class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               FitGaussian are implemented in this file.
//
// project :     Fit Gaussian
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <FitGaussian.h>
#include <FitGaussianClass.h>

/*----- PROTECTED REGION END -----*/	//	FitGaussian.cpp

/**
 *  FitGaussian class description:
 *    Compute a Gaussian Fit according to Levenberg Marquardt method
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//  State         |  dev_state
//  Status        |  Inherited (no method)
//================================================================

//================================================================
//  Attributes managed are:
//================================================================
//  version            |  Tango::DevString	Scalar
//  operationType      |  Tango::DevString	Scalar
//  FitEnabled         |  Tango::DevBoolean	Scalar
//  AutoROIEnabled     |  Tango::DevBoolean	Scalar
//  AutoROIFound       |  Tango::DevBoolean	Scalar
//  AutoROIOriginX     |  Tango::DevLong	Scalar
//  AutoROIOriginY     |  Tango::DevLong	Scalar
//  AutoROIWidth       |  Tango::DevLong	Scalar
//  AutoROIHeight      |  Tango::DevLong	Scalar
//  XProjEnabled       |  Tango::DevBoolean	Scalar
//  XProjFitConverged  |  Tango::DevBoolean	Scalar
//  XProjFitCenter     |  Tango::DevDouble	Scalar
//  XProjFitMag        |  Tango::DevDouble	Scalar
//  XProjFitSigma      |  Tango::DevDouble	Scalar
//  XProjFitFWHM       |  Tango::DevDouble	Scalar
//  XProjFitBG         |  Tango::DevDouble	Scalar
//  XProjFitChi2       |  Tango::DevDouble	Scalar
//  XProjFitNbIter     |  Tango::DevULong	Scalar
//  XProjPushTime      |  Tango::DevString	Scalar
//  YProjEnabled       |  Tango::DevBoolean	Scalar
//  YProjFitConverged  |  Tango::DevBoolean	Scalar
//  YProjFitCenter     |  Tango::DevDouble	Scalar
//  YProjFitMag        |  Tango::DevDouble	Scalar
//  YProjFitSigma      |  Tango::DevDouble	Scalar
//  YProjFitFWHM       |  Tango::DevDouble	Scalar
//  YProjFitBG         |  Tango::DevDouble	Scalar
//  YProjFitChi2       |  Tango::DevDouble	Scalar
//  YProjFitNbIter     |  Tango::DevULong	Scalar
//  YProjPushTime      |  Tango::DevString	Scalar
//  operationList      |  Tango::DevString	Spectrum  ( max = 1024)
//  XProj              |  Tango::DevDouble	Spectrum  ( max = 4096)
//  XProjFitted        |  Tango::DevDouble	Spectrum  ( max = 4096)
//  YProj              |  Tango::DevDouble	Spectrum  ( max = 4096)
//  YProjFitted        |  Tango::DevDouble	Spectrum  ( max = 4096)
//  ROIImage           |  Tango::DevUShort	Image  ( max = 4096 x 4096)
//================================================================

namespace FitGaussian_ns
{
/*----- PROTECTED REGION ID(FitGaussian::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	FitGaussian::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : FitGaussian::FitGaussian()
 *	Description : Constructors for a Tango device
 *                implementing the classFitGaussian
 */
//--------------------------------------------------------
FitGaussian::FitGaussian(Tango::DeviceClass *cl, string &s)
 : Tango::Device_4Impl(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(FitGaussian::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::constructor_1
}
//--------------------------------------------------------
FitGaussian::FitGaussian(Tango::DeviceClass *cl, const char *s)
 : Tango::Device_4Impl(cl, s)
{
	/*----- PROTECTED REGION ID(FitGaussian::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::constructor_2
}
//--------------------------------------------------------
FitGaussian::FitGaussian(Tango::DeviceClass *cl, const char *s, const char *d)
 : Tango::Device_4Impl(cl, s, d)
{
	/*----- PROTECTED REGION ID(FitGaussian::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : FitGaussian::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void FitGaussian::delete_device()
{
	DEBUG_STREAM << "FitGaussian::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(FitGaussian::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::delete_device
}

//--------------------------------------------------------
/**
 *	Method      : FitGaussian::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void FitGaussian::init_device()
{
	DEBUG_STREAM << "FitGaussian::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(FitGaussian::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::init_device_before
	

	//	Get the device properties from database
	get_device_property();
	

	/*----- PROTECTED REGION ID(FitGaussian::init_device) ENABLED START -----*/
	
	//	Initialize device
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::init_device
}

//--------------------------------------------------------
/**
 *	Method      : FitGaussian::get_device_property()
 *	Description : Read database to initialize property data members.
 */
//--------------------------------------------------------
void FitGaussian::get_device_property()
{
	/*----- PROTECTED REGION ID(FitGaussian::get_device_property_before) ENABLED START -----*/
	
	//	Initialize property data members
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::get_device_property_before


	//	Read device properties from database.
	Tango::DbData	dev_prop;
	dev_prop.push_back(Tango::DbDatum("FitEnabled"));
	dev_prop.push_back(Tango::DbDatum("AutoROIEnabled"));
	dev_prop.push_back(Tango::DbDatum("AutoROIMagnificationFactorX"));
	dev_prop.push_back(Tango::DbDatum("AutoROIMagnificationFactorY"));
	dev_prop.push_back(Tango::DbDatum("PixelSizeX"));
	dev_prop.push_back(Tango::DbDatum("PixelSizeY"));
	dev_prop.push_back(Tango::DbDatum("OpticalMagnification"));
	dev_prop.push_back(Tango::DbDatum("FitNbIterationsMax"));
	dev_prop.push_back(Tango::DbDatum("FitTolerance"));
	dev_prop.push_back(Tango::DbDatum("MemorizedOperationType"));
	dev_prop.push_back(Tango::DbDatum("MemorizedOperationLevel"));
	dev_prop.push_back(Tango::DbDatum("XProjEnabled"));
	dev_prop.push_back(Tango::DbDatum("YProjEnabled"));
	dev_prop.push_back(Tango::DbDatum("ProfileFitFixedBg"));
	dev_prop.push_back(Tango::DbDatum("RotationAngle"));
	dev_prop.push_back(Tango::DbDatum("DisplayRotatedImage"));

	//	is there at least one property to be read ?
	if (dev_prop.size()>0)
	{
		//	Call database and extract values
		if (Tango::Util::instance()->_UseDb==true)
			get_db_device()->get_property(dev_prop);
	
		//	get instance on FitGaussianClass to get class property
		Tango::DbDatum	def_prop, cl_prop;
		FitGaussianClass	*ds_class =
			(static_cast<FitGaussianClass *>(get_device_class()));
		int	i = -1;

		//	Try to initialize FitEnabled from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  fitEnabled;
		else {
			//	Try to initialize FitEnabled from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  fitEnabled;
		}
		//	And try to extract FitEnabled value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  fitEnabled;

		//	Try to initialize AutoROIEnabled from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  autoROIEnabled;
		else {
			//	Try to initialize AutoROIEnabled from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  autoROIEnabled;
		}
		//	And try to extract AutoROIEnabled value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  autoROIEnabled;

		//	Try to initialize AutoROIMagnificationFactorX from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  autoROIMagnificationFactorX;
		else {
			//	Try to initialize AutoROIMagnificationFactorX from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  autoROIMagnificationFactorX;
		}
		//	And try to extract AutoROIMagnificationFactorX value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  autoROIMagnificationFactorX;

		//	Try to initialize AutoROIMagnificationFactorY from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  autoROIMagnificationFactorY;
		else {
			//	Try to initialize AutoROIMagnificationFactorY from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  autoROIMagnificationFactorY;
		}
		//	And try to extract AutoROIMagnificationFactorY value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  autoROIMagnificationFactorY;

		//	Try to initialize PixelSizeX from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  pixelSizeX;
		else {
			//	Try to initialize PixelSizeX from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  pixelSizeX;
		}
		//	And try to extract PixelSizeX value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  pixelSizeX;

		//	Try to initialize PixelSizeY from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  pixelSizeY;
		else {
			//	Try to initialize PixelSizeY from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  pixelSizeY;
		}
		//	And try to extract PixelSizeY value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  pixelSizeY;

		//	Try to initialize OpticalMagnification from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  opticalMagnification;
		else {
			//	Try to initialize OpticalMagnification from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  opticalMagnification;
		}
		//	And try to extract OpticalMagnification value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  opticalMagnification;

		//	Try to initialize FitNbIterationsMax from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  fitNbIterationsMax;
		else {
			//	Try to initialize FitNbIterationsMax from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  fitNbIterationsMax;
		}
		//	And try to extract FitNbIterationsMax value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  fitNbIterationsMax;

		//	Try to initialize FitTolerance from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  fitTolerance;
		else {
			//	Try to initialize FitTolerance from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  fitTolerance;
		}
		//	And try to extract FitTolerance value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  fitTolerance;

		//	Try to initialize MemorizedOperationType from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  memorizedOperationType;
		else {
			//	Try to initialize MemorizedOperationType from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  memorizedOperationType;
		}
		//	And try to extract MemorizedOperationType value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  memorizedOperationType;

		//	Try to initialize MemorizedOperationLevel from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  memorizedOperationLevel;
		else {
			//	Try to initialize MemorizedOperationLevel from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  memorizedOperationLevel;
		}
		//	And try to extract MemorizedOperationLevel value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  memorizedOperationLevel;

		//	Try to initialize XProjEnabled from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  xProjEnabled;
		else {
			//	Try to initialize XProjEnabled from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  xProjEnabled;
		}
		//	And try to extract XProjEnabled value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  xProjEnabled;

		//	Try to initialize YProjEnabled from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  yProjEnabled;
		else {
			//	Try to initialize YProjEnabled from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  yProjEnabled;
		}
		//	And try to extract YProjEnabled value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  yProjEnabled;

		//	Try to initialize ProfileFitFixedBg from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  profileFitFixedBg;
		else {
			//	Try to initialize ProfileFitFixedBg from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  profileFitFixedBg;
		}
		//	And try to extract ProfileFitFixedBg value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  profileFitFixedBg;

		//	Try to initialize RotationAngle from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  rotationAngle;
		else {
			//	Try to initialize RotationAngle from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  rotationAngle;
		}
		//	And try to extract RotationAngle value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  rotationAngle;

		//	Try to initialize DisplayRotatedImage from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  displayRotatedImage;
		else {
			//	Try to initialize DisplayRotatedImage from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  displayRotatedImage;
		}
		//	And try to extract DisplayRotatedImage value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  displayRotatedImage;

	}

	/*----- PROTECTED REGION ID(FitGaussian::get_device_property_after) ENABLED START -----*/
	
	//	Check device property data members init
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::get_device_property_after
}

//--------------------------------------------------------
/**
 *	Method      : FitGaussian::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void FitGaussian::always_executed_hook()
{
	INFO_STREAM << "FitGaussian::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(FitGaussian::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : FitGaussian::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void FitGaussian::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "FitGaussian::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute version related method
 *	Description: FitGaussian device Version
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::read_version(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_version(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_version) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_version_read);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_version
}
//--------------------------------------------------------
/**
 *	Read attribute operationType related method
 *	Description: Indicates which operation type is applied (NONE or FIT).
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::read_operationType(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_operationType(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_operationType) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_operationType_read);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_operationType
}
//--------------------------------------------------------
/**
 *	Write attribute FitEnabled related method
 *	Description: Enable/Disable Fit Gaussian.
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::write_FitEnabled(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "FitGaussian::write_FitEnabled(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevBoolean	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(FitGaussian::write_FitEnabled) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::write_FitEnabled
}
//--------------------------------------------------------
/**
 *	Write attribute AutoROIEnabled related method
 *	Description: Enable/Disable Auto ROI.
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::write_AutoROIEnabled(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "FitGaussian::write_AutoROIEnabled(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevBoolean	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(FitGaussian::write_AutoROIEnabled) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::write_AutoROIEnabled
}
//--------------------------------------------------------
/**
 *	Read attribute AutoROIFound related method
 *	Description: Indicates whether the automatic ROI detection was successful.
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::read_AutoROIFound(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_AutoROIFound(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_AutoROIFound) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_AutoROIFound_read);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_AutoROIFound
}
//--------------------------------------------------------
/**
 *	Read attribute AutoROIOriginX related method
 *	Description: The coordinate of the ROI: OriginX.
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::read_AutoROIOriginX(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_AutoROIOriginX(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_AutoROIOriginX) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_AutoROIOriginX_read);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_AutoROIOriginX
}
//--------------------------------------------------------
/**
 *	Read attribute AutoROIOriginY related method
 *	Description: The coordinate of the ROI: OriginY.
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::read_AutoROIOriginY(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_AutoROIOriginY(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_AutoROIOriginY) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_AutoROIOriginY_read);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_AutoROIOriginY
}
//--------------------------------------------------------
/**
 *	Read attribute AutoROIWidth related method
 *	Description: The coordinate of the ROI: Width.
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::read_AutoROIWidth(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_AutoROIWidth(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_AutoROIWidth) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_AutoROIWidth_read);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_AutoROIWidth
}
//--------------------------------------------------------
/**
 *	Read attribute AutoROIHeight related method
 *	Description: The coordinate of the ROI: Height.
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::read_AutoROIHeight(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_AutoROIHeight(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_AutoROIHeight) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_AutoROIHeight_read);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_AutoROIHeight
}
//--------------------------------------------------------
/**
 *	Write attribute XProjEnabled related method
 *	Description: Enable/Disable fitting along this axis.
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::write_XProjEnabled(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "FitGaussian::write_XProjEnabled(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevBoolean	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(FitGaussian::write_XProjEnabled) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::write_XProjEnabled
}
//--------------------------------------------------------
/**
 *	Read attribute XProjFitConverged related method
 *	Description: Indicates whether the projection fitting algorithm has converged along this axis.
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::read_XProjFitConverged(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_XProjFitConverged(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_XProjFitConverged) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_XProjFitConverged_read);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_XProjFitConverged
}
//--------------------------------------------------------
/**
 *	Read attribute XProjFitCenter related method
 *	Description: The coordinate of the center of the fitted Gaussian along this axis.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::read_XProjFitCenter(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_XProjFitCenter(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_XProjFitCenter) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_XProjFitCenter_read);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_XProjFitCenter
}
//--------------------------------------------------------
/**
 *	Read attribute XProjFitMag related method
 *	Description: The magnitude of  fitted gaussian along this axis.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::read_XProjFitMag(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_XProjFitMag(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_XProjFitMag) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_XProjFitMag_read);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_XProjFitMag
}
//--------------------------------------------------------
/**
 *	Read attribute XProjFitSigma related method
 *	Description: The standard deviation of the fitted Gaussian along this axis.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::read_XProjFitSigma(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_XProjFitSigma(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_XProjFitSigma) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_XProjFitSigma_read);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_XProjFitSigma
}
//--------------------------------------------------------
/**
 *	Read attribute XProjFitFWHM related method
 *	Description: The full width at half maximum of the fitted Gaussian along this axis, calculated as approximately 2.35 × the fitted Gaussian standard deviation.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::read_XProjFitFWHM(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_XProjFitFWHM(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_XProjFitFWHM) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_XProjFitFWHM_read);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_XProjFitFWHM
}
//--------------------------------------------------------
/**
 *	Read attribute XProjFitBG related method
 *	Description: The background of  fitted gaussian along this axis.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::read_XProjFitBG(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_XProjFitBG(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_XProjFitBG) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_XProjFitBG_read);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_XProjFitBG
}
//--------------------------------------------------------
/**
 *	Read attribute XProjFitChi2 related method
 *	Description: The chi2 of the fitted Gaussian along this axis.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::read_XProjFitChi2(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_XProjFitChi2(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_XProjFitChi2) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_XProjFitChi2_read);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_XProjFitChi2
}
//--------------------------------------------------------
/**
 *	Read attribute XProjFitNbIter related method
 *	Description: The number of iterations used for fitting along this axis.
 *
 *	Data type:	Tango::DevULong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::read_XProjFitNbIter(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_XProjFitNbIter(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_XProjFitNbIter) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_XProjFitNbIter_read);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_XProjFitNbIter
}
//--------------------------------------------------------
/**
 *	Read attribute XProjPushTime related method
 *	Description: The Timestamp at which the sigma value was pushed for this axis.
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::read_XProjPushTime(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_XProjPushTime(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_XProjPushTime) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_XProjPushTime_read);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_XProjPushTime
}
//--------------------------------------------------------
/**
 *	Write attribute YProjEnabled related method
 *	Description: Enable/Disable fitting along this axis.
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::write_YProjEnabled(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "FitGaussian::write_YProjEnabled(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevBoolean	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(FitGaussian::write_YProjEnabled) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::write_YProjEnabled
}
//--------------------------------------------------------
/**
 *	Read attribute YProjFitConverged related method
 *	Description: Indicates whether the projection fitting algorithm has converged along this axis.
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::read_YProjFitConverged(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_YProjFitConverged(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_YProjFitConverged) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_YProjFitConverged_read);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_YProjFitConverged
}
//--------------------------------------------------------
/**
 *	Read attribute YProjFitCenter related method
 *	Description: The coordinate of the center of the fitted Gaussian along this axis.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::read_YProjFitCenter(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_YProjFitCenter(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_YProjFitCenter) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_YProjFitCenter_read);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_YProjFitCenter
}
//--------------------------------------------------------
/**
 *	Read attribute YProjFitMag related method
 *	Description: The magnitude of  fitted gaussian along this axis.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::read_YProjFitMag(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_YProjFitMag(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_YProjFitMag) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_YProjFitMag_read);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_YProjFitMag
}
//--------------------------------------------------------
/**
 *	Read attribute YProjFitSigma related method
 *	Description: The standard deviation of the fitted Gaussian corresponding along this axis.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::read_YProjFitSigma(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_YProjFitSigma(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_YProjFitSigma) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_YProjFitSigma_read);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_YProjFitSigma
}
//--------------------------------------------------------
/**
 *	Read attribute YProjFitFWHM related method
 *	Description: The full width at half maximum of the fitted Gaussian along this axis, calculated as approximately 2.35 × the fitted Gaussian standard deviation.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::read_YProjFitFWHM(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_YProjFitFWHM(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_YProjFitFWHM) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_YProjFitFWHM_read);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_YProjFitFWHM
}
//--------------------------------------------------------
/**
 *	Read attribute YProjFitBG related method
 *	Description: The background of  fitted gaussian along this axis.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::read_YProjFitBG(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_YProjFitBG(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_YProjFitBG) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_YProjFitBG_read);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_YProjFitBG
}
//--------------------------------------------------------
/**
 *	Read attribute YProjFitChi2 related method
 *	Description: The chi-square of the fitted Gaussian along this axis.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::read_YProjFitChi2(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_YProjFitChi2(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_YProjFitChi2) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_YProjFitChi2_read);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_YProjFitChi2
}
//--------------------------------------------------------
/**
 *	Read attribute YProjFitNbIter related method
 *	Description: The number of iterations used for fitting along this axis.
 *
 *	Data type:	Tango::DevULong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::read_YProjFitNbIter(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_YProjFitNbIter(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_YProjFitNbIter) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_YProjFitNbIter_read);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_YProjFitNbIter
}
//--------------------------------------------------------
/**
 *	Read attribute YProjPushTime related method
 *	Description: The Timestamp at which the sigma value was pushed for this axis.
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void FitGaussian::read_YProjPushTime(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_YProjPushTime(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_YProjPushTime) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_YProjPushTime_read);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_YProjPushTime
}
//--------------------------------------------------------
/**
 *	Read attribute operationList related method
 *	Description: Enumerate all FitGaussian active 'post processing' operations on the image.
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Spectrum max = 1024
 */
//--------------------------------------------------------
void FitGaussian::read_operationList(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_operationList(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_operationList) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_operationList_read, 1024);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_operationList
}
//--------------------------------------------------------
/**
 *	Read attribute XProj related method
 *	Description: The mean projection spectrum along this axis, with each point representing the average of all values projected onto this axis.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Spectrum max = 4096
 */
//--------------------------------------------------------
void FitGaussian::read_XProj(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_XProj(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_XProj) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_XProj_read, 4096);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_XProj
}
//--------------------------------------------------------
/**
 *	Read attribute XProjFitted related method
 *	Description: The Gaussian fit result along this axis.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Spectrum max = 4096
 */
//--------------------------------------------------------
void FitGaussian::read_XProjFitted(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_XProjFitted(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_XProjFitted) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_XProjFitted_read, 4096);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_XProjFitted
}
//--------------------------------------------------------
/**
 *	Read attribute YProj related method
 *	Description: The mean projection spectrum along this axis, with each point representing the average of all values projected onto this axis.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Spectrum max = 4096
 */
//--------------------------------------------------------
void FitGaussian::read_YProj(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_YProj(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_YProj) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_YProj_read, 4096);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_YProj
}
//--------------------------------------------------------
/**
 *	Read attribute YProjFitted related method
 *	Description: The Gaussian fit result along this axis.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Spectrum max = 4096
 */
//--------------------------------------------------------
void FitGaussian::read_YProjFitted(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_YProjFitted(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_YProjFitted) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_YProjFitted_read, 4096);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_YProjFitted
}
//--------------------------------------------------------
/**
 *	Read attribute ROIImage related method
 *	Description: The image with the ROI detected by AutoRoi.
 *
 *	Data type:	Tango::DevUShort
 *	Attr type:	Image max = 4096 x 4096
 */
//--------------------------------------------------------
void FitGaussian::read_ROIImage(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FitGaussian::read_ROIImage(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FitGaussian::read_ROIImage) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_ROIImage_read, 4096, 4096);
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::read_ROIImage
}

//--------------------------------------------------------
/**
 *	Method      : FitGaussian::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void FitGaussian::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(FitGaussian::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Command State related method
 *	Description: This command gets the device state (stored in its <i>device_state</i> data member) and returns it to the caller.
 *
 *	@returns State Code
 */
//--------------------------------------------------------
Tango::DevState FitGaussian::dev_state()
{
	DEBUG_STREAM << "FitGaussian::State()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(FitGaussian::dev_state) ENABLED START -----*/
	
	Tango::DevState	argout = Tango::UNKNOWN; // replace by your own algorithm
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	FitGaussian::dev_state
	set_state(argout);    // Give the state to Tango.
	if (argout!=Tango::ALARM)
		DeviceImpl::dev_state();
	return get_state();  // Return it after Tango management.
}

/*----- PROTECTED REGION ID(FitGaussian::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	FitGaussian::namespace_ending
} //	namespace
