/*----- PROTECTED REGION ID(Mask.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        Mask.cpp
//
// description : C++ source for the Mask class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               Mask are implemented in this file.
//
// project :     Lima
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <Mask.h>
#include <MaskClass.h>

/*----- PROTECTED REGION END -----*/	//	Mask.cpp

/**
 *  Mask class description:
 *    
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//  State         |  dev_state
//  Status        |  Inherited (no method)
//================================================================

//================================================================
//  Attributes managed are:
//================================================================
//  version         |  Tango::DevString	Scalar
//  runLevel        |  Tango::DevULong	Scalar
//  operationsList  |  Tango::DevString	Spectrum  ( max = 1024)
//  maskImage       |  Tango::DevShort	Image  ( max = 10000 x 10000)
//================================================================

namespace Mask_ns
{
/*----- PROTECTED REGION ID(Mask::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	Mask::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : Mask::Mask()
 *	Description : Constructors for a Tango device
 *                implementing the classMask
 */
//--------------------------------------------------------
Mask::Mask(Tango::DeviceClass *cl, string &s)
 : Tango::Device_4Impl(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(Mask::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	Mask::constructor_1
}
//--------------------------------------------------------
Mask::Mask(Tango::DeviceClass *cl, const char *s)
 : Tango::Device_4Impl(cl, s)
{
	/*----- PROTECTED REGION ID(Mask::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	Mask::constructor_2
}
//--------------------------------------------------------
Mask::Mask(Tango::DeviceClass *cl, const char *s, const char *d)
 : Tango::Device_4Impl(cl, s, d)
{
	/*----- PROTECTED REGION ID(Mask::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	Mask::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : Mask::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void Mask::delete_device()
{
	DEBUG_STREAM << "Mask::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(Mask::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	
	/*----- PROTECTED REGION END -----*/	//	Mask::delete_device
}

//--------------------------------------------------------
/**
 *	Method      : Mask::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void Mask::init_device()
{
	DEBUG_STREAM << "Mask::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(Mask::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	Mask::init_device_before
	

	//	Get the device properties from database
	get_device_property();
	

	/*----- PROTECTED REGION ID(Mask::init_device) ENABLED START -----*/
	
	//	Initialize device
	
	/*----- PROTECTED REGION END -----*/	//	Mask::init_device
}

//--------------------------------------------------------
/**
 *	Method      : Mask::get_device_property()
 *	Description : Read database to initialize property data members.
 */
//--------------------------------------------------------
void Mask::get_device_property()
{
	/*----- PROTECTED REGION ID(Mask::get_device_property_before) ENABLED START -----*/
	
	//	Initialize property data members
	
	/*----- PROTECTED REGION END -----*/	//	Mask::get_device_property_before


	//	Read device properties from database.
	Tango::DbData	dev_prop;
	dev_prop.push_back(Tango::DbDatum("MemorizedRunLevel"));

	//	is there at least one property to be read ?
	if (dev_prop.size()>0)
	{
		//	Call database and extract values
		if (Tango::Util::instance()->_UseDb==true)
			get_db_device()->get_property(dev_prop);
	
		//	get instance on MaskClass to get class property
		Tango::DbDatum	def_prop, cl_prop;
		MaskClass	*ds_class =
			(static_cast<MaskClass *>(get_device_class()));
		int	i = -1;

		//	Try to initialize MemorizedRunLevel from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  memorizedRunLevel;
		else {
			//	Try to initialize MemorizedRunLevel from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  memorizedRunLevel;
		}
		//	And try to extract MemorizedRunLevel value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  memorizedRunLevel;

	}

	/*----- PROTECTED REGION ID(Mask::get_device_property_after) ENABLED START -----*/
	
	//	Check device property data members init
	
	/*----- PROTECTED REGION END -----*/	//	Mask::get_device_property_after
}

//--------------------------------------------------------
/**
 *	Method      : Mask::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void Mask::always_executed_hook()
{
	INFO_STREAM << "Mask::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(Mask::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	Mask::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : Mask::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void Mask::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "Mask::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(Mask::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Mask::read_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute version related method
 *	Description: Display the Version of the Mask Device
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Mask::read_version(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Mask::read_version(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Mask::read_version) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_version_read);
	
	/*----- PROTECTED REGION END -----*/	//	Mask::read_version
}
//--------------------------------------------------------
/**
 *	Write attribute runLevel related method
 *	Description: Fix the execution order of this operation in the processing chain
 *
 *	Data type:	Tango::DevULong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Mask::write_runLevel(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "Mask::write_runLevel(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevULong	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(Mask::write_runLevel) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	Mask::write_runLevel
}
//--------------------------------------------------------
/**
 *	Read attribute operationsList related method
 *	Description: Enumerate all Mask active 'post processing' operations on the image.
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Spectrum max = 1024
 */
//--------------------------------------------------------
void Mask::read_operationsList(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Mask::read_operationsList(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Mask::read_operationsList) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_operationsList_read, 1024);
	
	/*----- PROTECTED REGION END -----*/	//	Mask::read_operationsList
}
//--------------------------------------------------------
/**
 *	Read attribute maskImage related method
 *	Description: Define the mask image for the Mask Processing 
 *
 *	Data type:	Tango::DevShort
 *	Attr type:	Image max = 10000 x 10000
 */
//--------------------------------------------------------
void Mask::read_maskImage(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Mask::read_maskImage(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Mask::read_maskImage) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_maskImage_read, 10000, 10000);
	
	/*----- PROTECTED REGION END -----*/	//	Mask::read_maskImage
}
//--------------------------------------------------------
/**
 *	Write attribute maskImage related method
 *	Description: Define the mask image for the Mask Processing 
 *
 *	Data type:	Tango::DevShort
 *	Attr type:	Image max = 10000 x 10000
 */
//--------------------------------------------------------
void Mask::write_maskImage(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "Mask::write_maskImage(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve number of write values
	int	w_length = attr.get_write_value_length();

	//	Retrieve pointer on write values (Do not delete !)
	const Tango::DevShort	*w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(Mask::write_maskImage) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	Mask::write_maskImage
}

//--------------------------------------------------------
/**
 *	Method      : Mask::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void Mask::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(Mask::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	Mask::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Command State related method
 *	Description: This command gets the device state (stored in its <i>device_state</i> data member) and returns it to the caller.
 *
 *	@returns State Code
 */
//--------------------------------------------------------
Tango::DevState Mask::dev_state()
{
	DEBUG_STREAM << "Mask::State()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(Mask::dev_state) ENABLED START -----*/
	
	Tango::DevState	argout = Tango::UNKNOWN; // replace by your own algorithm
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Mask::dev_state
	set_state(argout);    // Give the state to Tango.
	if (argout!=Tango::ALARM)
		DeviceImpl::dev_state();
	return get_state();  // Return it after Tango management.
}

/*----- PROTECTED REGION ID(Mask::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	Mask::namespace_ending
} //	namespace
