/*----- PROTECTED REGION ID(Rixs.h) ENABLED START -----*/
//=============================================================================
//
// file :        Rixs.h
//
// description : Include file for the Rixs class
//
// project :     Lima Rixs Device Specific
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef Rixs_H
#define Rixs_H

#include <tango.h>


/*----- PROTECTED REGION END -----*/	//	Rixs.h

/**
 *  Rixs class description:
 *    Lima Device Specific for post process image
 */

namespace Rixs_ns
{
/*----- PROTECTED REGION ID(Rixs::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	Rixs::Additional Class Declarations

class Rixs : public Tango::Device_4Impl
{

/*----- PROTECTED REGION ID(Rixs::Data Members) ENABLED START -----*/

//	Add your own data members

/*----- PROTECTED REGION END -----*/	//	Rixs::Data Members

//	Device property data members
public:
	//	MemorizedOperationTypes:	Memorize all operationType declared in the order to process the image.
	vector<string>	memorizedOperationTypes;
	//	MemorizedOperationValues:	Memorize all operationValue associated to the operationType declared in the order to process the image.
	vector<string>	memorizedOperationValues;
	//	MemorizedOperationLevels:	Memorize all levels associated to the operationType declared in the order to process the image.
	vector<Tango::DevLong>	memorizedOperationLevels;
	//	ResetSpectrumsAtEachFrame:	All Spectrum data wil be reset at each new Frame
	Tango::DevBoolean	resetSpectrumsAtEachFrame;
	//	DefaultValueInSpectrumsIfEmpty:	Set default value (-1) in spectrums if there is 0 Valid Clusters
	Tango::DevBoolean	defaultValueInSpectrumsIfEmpty;
	//	RixsDrawCentroidColor:	RIXS : Define Color of centroids
	string	rixsDrawCentroidColor;
	//	RixsDrawClusterColor:	RIXS : Define Color of Clusters
	string	rixsDrawClusterColor;

//	Attribute data members
public:
	Tango::DevString	*attr_version_read;
	Tango::DevString	*attr_operationType_read;
	Tango::DevString	*attr_operationValue_read;
	Tango::DevLong	*attr_nbClusterValid_read;
	Tango::DevString	*attr_operationsList_read;
	Tango::DevLong	*attr_clusterCounter_read;
	Tango::DevLong	*attr_clusterArea_read;
	Tango::DevLong	*attr_clusterSum_read;
	Tango::DevDouble	*attr_clusterCentroidX_read;
	Tango::DevDouble	*attr_clusterCentroidY_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	Rixs(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	Rixs(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	Rixs(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */	
	~Rixs() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : Rixs::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute version related methods
 *	Description: Display the Version
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_version(Tango::Attribute &attr);
	virtual bool is_version_allowed(Tango::AttReqType type);
/**
 *	Attribute operationType related methods
 *	Description: available types :<br>\nRIXS<br>\nNONE<br>
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_operationType(Tango::Attribute &attr);
	virtual void write_operationType(Tango::WAttribute &attr);
	virtual bool is_operationType_allowed(Tango::AttReqType type);
/**
 *	Attribute operationValue related methods
 *	Description: Arithmetic available values :<br>\nany numeric value\n\n
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_operationValue(Tango::Attribute &attr);
	virtual void write_operationValue(Tango::WAttribute &attr);
	virtual bool is_operationValue_allowed(Tango::AttReqType type);
/**
 *	Attribute minAreaCluster related methods
 *	Description: Define the Min Area accepted for a Cluster.<CR>\n-1 to disable control of Min Area
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void write_minAreaCluster(Tango::WAttribute &attr);
	virtual bool is_minAreaCluster_allowed(Tango::AttReqType type);
/**
 *	Attribute maxAreaCluster related methods
 *	Description: Define the Max Area accepted for a Cluster.<CR>\n-1 to disable control of Max Area
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void write_maxAreaCluster(Tango::WAttribute &attr);
	virtual bool is_maxAreaCluster_allowed(Tango::AttReqType type);
/**
 *	Attribute nbClusterValid related methods
 *	Description: Nombre of valid clusters
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_nbClusterValid(Tango::Attribute &attr);
	virtual bool is_nbClusterValid_allowed(Tango::AttReqType type);
/**
 *	Attribute drawClusterEnabled related methods
 *	Description: Enable/Disable drawing Rect on Valid Clusters
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void write_drawClusterEnabled(Tango::WAttribute &attr);
	virtual bool is_drawClusterEnabled_allowed(Tango::AttReqType type);
/**
 *	Attribute drawCentroidEnabled related methods
 *	Description: Enable/Disable drawing Circle on Centroids of Valid Clusters
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void write_drawCentroidEnabled(Tango::WAttribute &attr);
	virtual bool is_drawCentroidEnabled_allowed(Tango::AttReqType type);
/**
 *	Attribute pngFilesEnabled related methods
 *	Description: Enable/Disable writing results in PNG files
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void write_pngFilesEnabled(Tango::WAttribute &attr);
	virtual bool is_pngFilesEnabled_allowed(Tango::AttReqType type);
/**
 *	Attribute pngFilesPath related methods
 *	Description: Path of PNG files 
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void write_pngFilesPath(Tango::WAttribute &attr);
	virtual bool is_pngFilesPath_allowed(Tango::AttReqType type);
/**
 *	Attribute operationsList related methods
 *	Description: Enumerate all Rixs active 'post processing' operations on the image.
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Spectrum max = 1024
 */
	virtual void read_operationsList(Tango::Attribute &attr);
	virtual bool is_operationsList_allowed(Tango::AttReqType type);
/**
 *	Attribute clusterCounter related methods
 *	Description: 
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Spectrum max = 100000
 */
	virtual void read_clusterCounter(Tango::Attribute &attr);
	virtual bool is_clusterCounter_allowed(Tango::AttReqType type);
/**
 *	Attribute clusterArea related methods
 *	Description: 
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Spectrum max = 1000000
 */
	virtual void read_clusterArea(Tango::Attribute &attr);
	virtual bool is_clusterArea_allowed(Tango::AttReqType type);
/**
 *	Attribute clusterSum related methods
 *	Description: 
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Spectrum max = 1000000
 */
	virtual void read_clusterSum(Tango::Attribute &attr);
	virtual bool is_clusterSum_allowed(Tango::AttReqType type);
/**
 *	Attribute clusterCentroidX related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Spectrum max = 1000000
 */
	virtual void read_clusterCentroidX(Tango::Attribute &attr);
	virtual bool is_clusterCentroidX_allowed(Tango::AttReqType type);
/**
 *	Attribute clusterCentroidY related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Spectrum max = 1000000
 */
	virtual void read_clusterCentroidY(Tango::Attribute &attr);
	virtual bool is_clusterCentroidY_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : Rixs::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();



//	Command related methods
public:
	/**
	 *	Command AddOperation related method
	 *	Description: Add Lima external operation in order to transform the image acquired from the detector.<br>
	 *               User must first define the operationType, operationValue attributes<br>
	 *               argin will define the level of operation.
	 *
	 *	@param argin 
	 */
	virtual void add_operation(Tango::DevLong argin);
	virtual bool is_AddOperation_allowed(const CORBA::Any &any);
	/**
	 *	Command RemoveOperation related method
	 *	Description: Remove a Lima external operation previously defined at the the level = argin.<br>
	 *
	 *	@param argin 
	 */
	virtual void remove_operation(Tango::DevLong argin);
	virtual bool is_RemoveOperation_allowed(const CORBA::Any &any);


/*----- PROTECTED REGION ID(Rixs::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes

/*----- PROTECTED REGION END -----*/	//	Rixs::Additional Method prototypes
};

/*----- PROTECTED REGION ID(Rixs::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	Rixs::Additional Classes Definitions

}	//	End of namespace

#endif   //	Rixs_H
