/*----- PROTECTED REGION ID(Rixs.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        Rixs.cpp
//
// description : C++ source for the Rixs class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               Rixs are implemented in this file.
//
// project :     Lima Rixs Device Specific
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <Rixs.h>
#include <RixsClass.h>

/*----- PROTECTED REGION END -----*/	//	Rixs.cpp

/**
 *  Rixs class description:
 *    Lima Device Specific for post process image
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name     |  Method name
//================================================================
//  State            |  Inherited (no method)
//  Status           |  Inherited (no method)
//  AddOperation     |  add_operation
//  RemoveOperation  |  remove_operation
//================================================================

//================================================================
//  Attributes managed are:
//================================================================
//  version              |  Tango::DevString	Scalar
//  operationType        |  Tango::DevString	Scalar
//  operationValue       |  Tango::DevString	Scalar
//  minAreaCluster       |  Tango::DevLong	Scalar
//  maxAreaCluster       |  Tango::DevLong	Scalar
//  nbClusterValid       |  Tango::DevLong	Scalar
//  drawClusterEnabled   |  Tango::DevBoolean	Scalar
//  drawCentroidEnabled  |  Tango::DevBoolean	Scalar
//  pngFilesEnabled      |  Tango::DevBoolean	Scalar
//  pngFilesPath         |  Tango::DevString	Scalar
//  operationsList       |  Tango::DevString	Spectrum  ( max = 1024)
//  clusterCounter       |  Tango::DevLong	Spectrum  ( max = 100000)
//  clusterArea          |  Tango::DevLong	Spectrum  ( max = 1000000)
//  clusterSum           |  Tango::DevLong	Spectrum  ( max = 1000000)
//  clusterCentroidX     |  Tango::DevDouble	Spectrum  ( max = 1000000)
//  clusterCentroidY     |  Tango::DevDouble	Spectrum  ( max = 1000000)
//================================================================

namespace Rixs_ns
{
/*----- PROTECTED REGION ID(Rixs::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	Rixs::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : Rixs::Rixs()
 *	Description : Constructors for a Tango device
 *                implementing the classRixs
 */
//--------------------------------------------------------
Rixs::Rixs(Tango::DeviceClass *cl, string &s)
 : Tango::Device_4Impl(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(Rixs::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::constructor_1
}
//--------------------------------------------------------
Rixs::Rixs(Tango::DeviceClass *cl, const char *s)
 : Tango::Device_4Impl(cl, s)
{
	/*----- PROTECTED REGION ID(Rixs::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::constructor_2
}
//--------------------------------------------------------
Rixs::Rixs(Tango::DeviceClass *cl, const char *s, const char *d)
 : Tango::Device_4Impl(cl, s, d)
{
	/*----- PROTECTED REGION ID(Rixs::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : Rixs::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void Rixs::delete_device()
{
	DEBUG_STREAM << "Rixs::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(Rixs::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::delete_device
}

//--------------------------------------------------------
/**
 *	Method      : Rixs::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void Rixs::init_device()
{
	DEBUG_STREAM << "Rixs::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(Rixs::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::init_device_before
	

	//	Get the device properties from database
	get_device_property();
	

	/*----- PROTECTED REGION ID(Rixs::init_device) ENABLED START -----*/
	
	//	Initialize device
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::init_device
}

//--------------------------------------------------------
/**
 *	Method      : Rixs::get_device_property()
 *	Description : Read database to initialize property data members.
 */
//--------------------------------------------------------
void Rixs::get_device_property()
{
	/*----- PROTECTED REGION ID(Rixs::get_device_property_before) ENABLED START -----*/
	
	//	Initialize property data members
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::get_device_property_before


	//	Read device properties from database.
	Tango::DbData	dev_prop;
	dev_prop.push_back(Tango::DbDatum("MemorizedOperationTypes"));
	dev_prop.push_back(Tango::DbDatum("MemorizedOperationValues"));
	dev_prop.push_back(Tango::DbDatum("MemorizedOperationLevels"));
	dev_prop.push_back(Tango::DbDatum("ResetSpectrumsAtEachFrame"));
	dev_prop.push_back(Tango::DbDatum("DefaultValueInSpectrumsIfEmpty"));
	dev_prop.push_back(Tango::DbDatum("RixsDrawCentroidColor"));
	dev_prop.push_back(Tango::DbDatum("RixsDrawClusterColor"));

	//	is there at least one property to be read ?
	if (dev_prop.size()>0)
	{
		//	Call database and extract values
		if (Tango::Util::instance()->_UseDb==true)
			get_db_device()->get_property(dev_prop);
	
		//	get instance on RixsClass to get class property
		Tango::DbDatum	def_prop, cl_prop;
		RixsClass	*ds_class =
			(static_cast<RixsClass *>(get_device_class()));
		int	i = -1;

		//	Try to initialize MemorizedOperationTypes from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  memorizedOperationTypes;
		else {
			//	Try to initialize MemorizedOperationTypes from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  memorizedOperationTypes;
		}
		//	And try to extract MemorizedOperationTypes value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  memorizedOperationTypes;

		//	Try to initialize MemorizedOperationValues from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  memorizedOperationValues;
		else {
			//	Try to initialize MemorizedOperationValues from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  memorizedOperationValues;
		}
		//	And try to extract MemorizedOperationValues value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  memorizedOperationValues;

		//	Try to initialize MemorizedOperationLevels from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  memorizedOperationLevels;
		else {
			//	Try to initialize MemorizedOperationLevels from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  memorizedOperationLevels;
		}
		//	And try to extract MemorizedOperationLevels value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  memorizedOperationLevels;

		//	Try to initialize ResetSpectrumsAtEachFrame from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  resetSpectrumsAtEachFrame;
		else {
			//	Try to initialize ResetSpectrumsAtEachFrame from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  resetSpectrumsAtEachFrame;
		}
		//	And try to extract ResetSpectrumsAtEachFrame value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  resetSpectrumsAtEachFrame;

		//	Try to initialize DefaultValueInSpectrumsIfEmpty from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  defaultValueInSpectrumsIfEmpty;
		else {
			//	Try to initialize DefaultValueInSpectrumsIfEmpty from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  defaultValueInSpectrumsIfEmpty;
		}
		//	And try to extract DefaultValueInSpectrumsIfEmpty value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  defaultValueInSpectrumsIfEmpty;

		//	Try to initialize RixsDrawCentroidColor from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  rixsDrawCentroidColor;
		else {
			//	Try to initialize RixsDrawCentroidColor from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  rixsDrawCentroidColor;
		}
		//	And try to extract RixsDrawCentroidColor value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  rixsDrawCentroidColor;

		//	Try to initialize RixsDrawClusterColor from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  rixsDrawClusterColor;
		else {
			//	Try to initialize RixsDrawClusterColor from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  rixsDrawClusterColor;
		}
		//	And try to extract RixsDrawClusterColor value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  rixsDrawClusterColor;

	}

	/*----- PROTECTED REGION ID(Rixs::get_device_property_after) ENABLED START -----*/
	
	//	Check device property data members init
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::get_device_property_after
}

//--------------------------------------------------------
/**
 *	Method      : Rixs::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void Rixs::always_executed_hook()
{
	INFO_STREAM << "Rixs::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(Rixs::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : Rixs::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void Rixs::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "Rixs::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(Rixs::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::read_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute version related method
 *	Description: Display the Version
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Rixs::read_version(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Rixs::read_version(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Rixs::read_version) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_version_read);
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::read_version
}
//--------------------------------------------------------
/**
 *	Read attribute operationType related method
 *	Description: available types :<br>\nRIXS<br>\nNONE<br>
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Rixs::read_operationType(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Rixs::read_operationType(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Rixs::read_operationType) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_operationType_read);
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::read_operationType
}
//--------------------------------------------------------
/**
 *	Write attribute operationType related method
 *	Description: available types :<br>\nRIXS<br>\nNONE<br>
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Rixs::write_operationType(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "Rixs::write_operationType(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevString	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(Rixs::write_operationType) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::write_operationType
}
//--------------------------------------------------------
/**
 *	Read attribute operationValue related method
 *	Description: Arithmetic available values :<br>\nany numeric value\n\n
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Rixs::read_operationValue(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Rixs::read_operationValue(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Rixs::read_operationValue) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_operationValue_read);
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::read_operationValue
}
//--------------------------------------------------------
/**
 *	Write attribute operationValue related method
 *	Description: Arithmetic available values :<br>\nany numeric value\n\n
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Rixs::write_operationValue(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "Rixs::write_operationValue(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevString	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(Rixs::write_operationValue) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::write_operationValue
}
//--------------------------------------------------------
/**
 *	Write attribute minAreaCluster related method
 *	Description: Define the Min Area accepted for a Cluster.<CR>\n-1 to disable control of Min Area
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Rixs::write_minAreaCluster(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "Rixs::write_minAreaCluster(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevLong	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(Rixs::write_minAreaCluster) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::write_minAreaCluster
}
//--------------------------------------------------------
/**
 *	Write attribute maxAreaCluster related method
 *	Description: Define the Max Area accepted for a Cluster.<CR>\n-1 to disable control of Max Area
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Rixs::write_maxAreaCluster(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "Rixs::write_maxAreaCluster(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevLong	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(Rixs::write_maxAreaCluster) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::write_maxAreaCluster
}
//--------------------------------------------------------
/**
 *	Read attribute nbClusterValid related method
 *	Description: Nombre of valid clusters
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Rixs::read_nbClusterValid(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Rixs::read_nbClusterValid(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Rixs::read_nbClusterValid) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_nbClusterValid_read);
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::read_nbClusterValid
}
//--------------------------------------------------------
/**
 *	Write attribute drawClusterEnabled related method
 *	Description: Enable/Disable drawing Rect on Valid Clusters
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Rixs::write_drawClusterEnabled(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "Rixs::write_drawClusterEnabled(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevBoolean	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(Rixs::write_drawClusterEnabled) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::write_drawClusterEnabled
}
//--------------------------------------------------------
/**
 *	Write attribute drawCentroidEnabled related method
 *	Description: Enable/Disable drawing Circle on Centroids of Valid Clusters
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Rixs::write_drawCentroidEnabled(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "Rixs::write_drawCentroidEnabled(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevBoolean	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(Rixs::write_drawCentroidEnabled) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::write_drawCentroidEnabled
}
//--------------------------------------------------------
/**
 *	Write attribute pngFilesEnabled related method
 *	Description: Enable/Disable writing results in PNG files
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Rixs::write_pngFilesEnabled(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "Rixs::write_pngFilesEnabled(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevBoolean	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(Rixs::write_pngFilesEnabled) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::write_pngFilesEnabled
}
//--------------------------------------------------------
/**
 *	Write attribute pngFilesPath related method
 *	Description: Path of PNG files 
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Rixs::write_pngFilesPath(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "Rixs::write_pngFilesPath(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevString	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(Rixs::write_pngFilesPath) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::write_pngFilesPath
}
//--------------------------------------------------------
/**
 *	Read attribute operationsList related method
 *	Description: Enumerate all Rixs active 'post processing' operations on the image.
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Spectrum max = 1024
 */
//--------------------------------------------------------
void Rixs::read_operationsList(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Rixs::read_operationsList(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Rixs::read_operationsList) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_operationsList_read, 1024);
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::read_operationsList
}
//--------------------------------------------------------
/**
 *	Read attribute clusterCounter related method
 *	Description: 
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Spectrum max = 100000
 */
//--------------------------------------------------------
void Rixs::read_clusterCounter(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Rixs::read_clusterCounter(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Rixs::read_clusterCounter) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_clusterCounter_read, 100000);
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::read_clusterCounter
}
//--------------------------------------------------------
/**
 *	Read attribute clusterArea related method
 *	Description: 
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Spectrum max = 1000000
 */
//--------------------------------------------------------
void Rixs::read_clusterArea(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Rixs::read_clusterArea(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Rixs::read_clusterArea) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_clusterArea_read, 1000000);
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::read_clusterArea
}
//--------------------------------------------------------
/**
 *	Read attribute clusterSum related method
 *	Description: 
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Spectrum max = 1000000
 */
//--------------------------------------------------------
void Rixs::read_clusterSum(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Rixs::read_clusterSum(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Rixs::read_clusterSum) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_clusterSum_read, 1000000);
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::read_clusterSum
}
//--------------------------------------------------------
/**
 *	Read attribute clusterCentroidX related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Spectrum max = 1000000
 */
//--------------------------------------------------------
void Rixs::read_clusterCentroidX(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Rixs::read_clusterCentroidX(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Rixs::read_clusterCentroidX) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_clusterCentroidX_read, 1000000);
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::read_clusterCentroidX
}
//--------------------------------------------------------
/**
 *	Read attribute clusterCentroidY related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Spectrum max = 1000000
 */
//--------------------------------------------------------
void Rixs::read_clusterCentroidY(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Rixs::read_clusterCentroidY(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Rixs::read_clusterCentroidY) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_clusterCentroidY_read, 1000000);
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::read_clusterCentroidY
}

//--------------------------------------------------------
/**
 *	Method      : Rixs::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void Rixs::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(Rixs::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Command AddOperation related method
 *	Description: Add Lima external operation in order to transform the image acquired from the detector.<br>
 *               User must first define the operationType, operationValue attributes<br>
 *               argin will define the level of operation.
 *
 *	@param argin 
 */
//--------------------------------------------------------
void Rixs::add_operation(Tango::DevLong argin)
{
	DEBUG_STREAM << "Rixs::AddOperation()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(Rixs::add_operation) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::add_operation
}
//--------------------------------------------------------
/**
 *	Command RemoveOperation related method
 *	Description: Remove a Lima external operation previously defined at the the level = argin.<br>
 *
 *	@param argin 
 */
//--------------------------------------------------------
void Rixs::remove_operation(Tango::DevLong argin)
{
	DEBUG_STREAM << "Rixs::RemoveOperation()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(Rixs::remove_operation) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Rixs::remove_operation
}

/*----- PROTECTED REGION ID(Rixs::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	Rixs::namespace_ending
} //	namespace
