/*----- PROTECTED REGION ID(RoiCounters.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        RoiCounters.cpp
//
// description : C++ source for the RoiCounters class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               RoiCounters are implemented in this file.
//
// project :     Lima
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <RoiCounters.h>
#include <RoiCountersClass.h>

/*----- PROTECTED REGION END -----*/	//	RoiCounters.cpp

/**
 *  RoiCounters class description:
 *    
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//  State         |  dev_state
//  Status        |  Inherited (no method)
//================================================================

//================================================================
//  Attributes managed are:
//================================================================
//  version         |  Tango::DevString	Scalar
//  runLevel        |  Tango::DevULong	Scalar
//  operationsList  |  Tango::DevString	Spectrum  ( max = 1024)
//================================================================

namespace RoiCounters_ns
{
/*----- PROTECTED REGION ID(RoiCounters::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	RoiCounters::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : RoiCounters::RoiCounters()
 *	Description : Constructors for a Tango device
 *                implementing the classRoiCounters
 */
//--------------------------------------------------------
RoiCounters::RoiCounters(Tango::DeviceClass *cl, string &s)
 : Tango::Device_4Impl(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(RoiCounters::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	RoiCounters::constructor_1
}
//--------------------------------------------------------
RoiCounters::RoiCounters(Tango::DeviceClass *cl, const char *s)
 : Tango::Device_4Impl(cl, s)
{
	/*----- PROTECTED REGION ID(RoiCounters::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	RoiCounters::constructor_2
}
//--------------------------------------------------------
RoiCounters::RoiCounters(Tango::DeviceClass *cl, const char *s, const char *d)
 : Tango::Device_4Impl(cl, s, d)
{
	/*----- PROTECTED REGION ID(RoiCounters::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	RoiCounters::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : RoiCounters::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void RoiCounters::delete_device()
{
	DEBUG_STREAM << "RoiCounters::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(RoiCounters::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	
	/*----- PROTECTED REGION END -----*/	//	RoiCounters::delete_device
}

//--------------------------------------------------------
/**
 *	Method      : RoiCounters::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void RoiCounters::init_device()
{
	DEBUG_STREAM << "RoiCounters::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(RoiCounters::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	RoiCounters::init_device_before
	

	//	Get the device properties from database
	get_device_property();
	

	/*----- PROTECTED REGION ID(RoiCounters::init_device) ENABLED START -----*/
	
	//	Initialize device
	
	/*----- PROTECTED REGION END -----*/	//	RoiCounters::init_device
}

//--------------------------------------------------------
/**
 *	Method      : RoiCounters::get_device_property()
 *	Description : Read database to initialize property data members.
 */
//--------------------------------------------------------
void RoiCounters::get_device_property()
{
	/*----- PROTECTED REGION ID(RoiCounters::get_device_property_before) ENABLED START -----*/
	
	//	Initialize property data members
	
	/*----- PROTECTED REGION END -----*/	//	RoiCounters::get_device_property_before


	//	Read device properties from database.
	Tango::DbData	dev_prop;
	dev_prop.push_back(Tango::DbDatum("NbRoiCounters"));
	dev_prop.push_back(Tango::DbDatum("__x"));
	dev_prop.push_back(Tango::DbDatum("__y"));
	dev_prop.push_back(Tango::DbDatum("__width"));
	dev_prop.push_back(Tango::DbDatum("__height"));
	dev_prop.push_back(Tango::DbDatum("ExpertSpectrumMaxDataSize"));
	dev_prop.push_back(Tango::DbDatum("MemorizedRunLevel"));

	//	is there at least one property to be read ?
	if (dev_prop.size()>0)
	{
		//	Call database and extract values
		if (Tango::Util::instance()->_UseDb==true)
			get_db_device()->get_property(dev_prop);
	
		//	get instance on RoiCountersClass to get class property
		Tango::DbDatum	def_prop, cl_prop;
		RoiCountersClass	*ds_class =
			(static_cast<RoiCountersClass *>(get_device_class()));
		int	i = -1;

		//	Try to initialize NbRoiCounters from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  nbRoiCounters;
		else {
			//	Try to initialize NbRoiCounters from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  nbRoiCounters;
		}
		//	And try to extract NbRoiCounters value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  nbRoiCounters;

		//	Try to initialize __x from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  __x;
		else {
			//	Try to initialize __x from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  __x;
		}
		//	And try to extract __x value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  __x;

		//	Try to initialize __y from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  __y;
		else {
			//	Try to initialize __y from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  __y;
		}
		//	And try to extract __y value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  __y;

		//	Try to initialize __width from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  __width;
		else {
			//	Try to initialize __width from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  __width;
		}
		//	And try to extract __width value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  __width;

		//	Try to initialize __height from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  __height;
		else {
			//	Try to initialize __height from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  __height;
		}
		//	And try to extract __height value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  __height;

		//	Try to initialize ExpertSpectrumMaxDataSize from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  expertSpectrumMaxDataSize;
		else {
			//	Try to initialize ExpertSpectrumMaxDataSize from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  expertSpectrumMaxDataSize;
		}
		//	And try to extract ExpertSpectrumMaxDataSize value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  expertSpectrumMaxDataSize;

		//	Try to initialize MemorizedRunLevel from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  memorizedRunLevel;
		else {
			//	Try to initialize MemorizedRunLevel from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  memorizedRunLevel;
		}
		//	And try to extract MemorizedRunLevel value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  memorizedRunLevel;

	}

	/*----- PROTECTED REGION ID(RoiCounters::get_device_property_after) ENABLED START -----*/
	
	//	Check device property data members init
	
	/*----- PROTECTED REGION END -----*/	//	RoiCounters::get_device_property_after
}

//--------------------------------------------------------
/**
 *	Method      : RoiCounters::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void RoiCounters::always_executed_hook()
{
	INFO_STREAM << "RoiCounters::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(RoiCounters::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	RoiCounters::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : RoiCounters::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void RoiCounters::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "RoiCounters::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(RoiCounters::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RoiCounters::read_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute version related method
 *	Description: Display the Version of the RoiCounters Device
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void RoiCounters::read_version(Tango::Attribute &attr)
{
	DEBUG_STREAM << "RoiCounters::read_version(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(RoiCounters::read_version) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_version_read);
	
	/*----- PROTECTED REGION END -----*/	//	RoiCounters::read_version
}
//--------------------------------------------------------
/**
 *	Write attribute runLevel related method
 *	Description: Fix the execution order of this operation in the processing chain
 *
 *	Data type:	Tango::DevULong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void RoiCounters::write_runLevel(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "RoiCounters::write_runLevel(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevULong	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(RoiCounters::write_runLevel) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	RoiCounters::write_runLevel
}
//--------------------------------------------------------
/**
 *	Read attribute operationsList related method
 *	Description: Enumerate all RoiCounters 'post processing' operations on the image.
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Spectrum max = 1024
 */
//--------------------------------------------------------
void RoiCounters::read_operationsList(Tango::Attribute &attr)
{
	DEBUG_STREAM << "RoiCounters::read_operationsList(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(RoiCounters::read_operationsList) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_operationsList_read, 1024);
	
	/*----- PROTECTED REGION END -----*/	//	RoiCounters::read_operationsList
}

//--------------------------------------------------------
/**
 *	Method      : RoiCounters::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void RoiCounters::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(RoiCounters::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	RoiCounters::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Command State related method
 *	Description: This command gets the device state (stored in its <i>device_state</i> data member) and returns it to the caller.
 *
 *	@returns State Code
 */
//--------------------------------------------------------
Tango::DevState RoiCounters::dev_state()
{
	DEBUG_STREAM << "RoiCounters::State()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(RoiCounters::dev_state) ENABLED START -----*/
	
	Tango::DevState	argout = Tango::UNKNOWN; // replace by your own algorithm
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RoiCounters::dev_state
	set_state(argout);    // Give the state to Tango.
	if (argout!=Tango::ALARM)
		DeviceImpl::dev_state();
	return get_state();  // Return it after Tango management.
}

/*----- PROTECTED REGION ID(RoiCounters::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	RoiCounters::namespace_ending
} //	namespace
