/*----- PROTECTED REGION ID(RoiCounters.h) ENABLED START -----*/
//=============================================================================
//
// file :        RoiCounters.h
//
// description : Include file for the RoiCounters class
//
// project :     Lima
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef RoiCounters_H
#define RoiCounters_H

#include <tango.h>


/*----- PROTECTED REGION END -----*/	//	RoiCounters.h

/**
 *  RoiCounters class description:
 *    
 */

namespace RoiCounters_ns
{
/*----- PROTECTED REGION ID(RoiCounters::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	RoiCounters::Additional Class Declarations

class RoiCounters : public Tango::Device_4Impl
{

/*----- PROTECTED REGION ID(RoiCounters::Data Members) ENABLED START -----*/

//	Add your own data members

/*----- PROTECTED REGION END -----*/	//	RoiCounters::Data Members

//	Device property data members
public:
	//	NbRoiCounters:	Fix the number of Region Of Interest.<br>
	//  Statistical calculations  (sum, average, std, min, max) will be made for these regions of interest.
	Tango::DevULong	nbRoiCounters;
	//	__x:	For each Region of Interest . (Origin X)
	vector<Tango::DevLong>	__x;
	//	__y:	For each Region of Interest . (Origin Y)
	vector<Tango::DevLong>	__y;
	//	__width:	For each Region of Interest . (Width)
	vector<Tango::DevLong>	__width;
	//	__height:	For each Region of Interest . (Height)
	vector<Tango::DevLong>	__height;
	//	ExpertSpectrumMaxDataSize:	Define the max number of points of spectrum attributes<br>
	Tango::DevULong	expertSpectrumMaxDataSize;
	//	MemorizedRunLevel:	Memorize/Define the runLevel attribute<br>
	Tango::DevULong	memorizedRunLevel;

//	Attribute data members
public:
	Tango::DevString	*attr_version_read;
	Tango::DevString	*attr_operationsList_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	RoiCounters(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	RoiCounters(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	RoiCounters(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */	
	~RoiCounters() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : RoiCounters::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute version related methods
 *	Description: Display the Version of the RoiCounters Device
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_version(Tango::Attribute &attr);
	virtual bool is_version_allowed(Tango::AttReqType type);
/**
 *	Attribute runLevel related methods
 *	Description: Fix the execution order of this operation in the processing chain
 *
 *	Data type:	Tango::DevULong
 *	Attr type:	Scalar
 */
	virtual void write_runLevel(Tango::WAttribute &attr);
	virtual bool is_runLevel_allowed(Tango::AttReqType type);
/**
 *	Attribute operationsList related methods
 *	Description: Enumerate all RoiCounters 'post processing' operations on the image.
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Spectrum max = 1024
 */
	virtual void read_operationsList(Tango::Attribute &attr);
	virtual bool is_operationsList_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : RoiCounters::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();



//	Command related methods
public:
	/**
	 *	Command State related method
	 *	Description: This command gets the device state (stored in its <i>device_state</i> data member) and returns it to the caller.
	 *
	 *	@returns State Code
	 */
	virtual Tango::DevState dev_state();


/*----- PROTECTED REGION ID(RoiCounters::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes

/*----- PROTECTED REGION END -----*/	//	RoiCounters::Additional Method prototypes
};

/*----- PROTECTED REGION ID(RoiCounters::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	RoiCounters::Additional Classes Definitions

}	//	End of namespace

#endif   //	RoiCounters_H
