/*----- PROTECTED REGION ID(LimaDetectorStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        LimaDetectorStateMachine.cpp
//
// description : State machine file for the LimaDetector class
//
// project :     Lima Device Generic
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#ifdef WIN32
#include <tango.h>
#endif

#include <LimaDetector.h>
#include <LimaDetectorClass.h>

#ifndef WIN32
#include <tango.h>
#endif

/*----- PROTECTED REGION END -----*/	//	LimaDetector::LimaDetectorStateMachine.cpp

//================================================================
//  States   |  Description
//================================================================
//  INIT     |  Error occured at the initialization of the device.<br>
//           |  It is mandatory to fix the errors and run the [ Init ] command of the LimaDetector device.<br>
//           |  The [ Snap ] command IS NOT available.<br>
//           |  The [ Start ] command IS NOT available.<br>
//           |  The [ Stop ] command IS NOT available.<br>
//           |  The [ SetRoi ] command IS NOT available.<br>
//           |  The [ SetBinning ] command IS NOT available.<br>
//  STANDBY  |  The Device is Waiting for a user request.<br>
//           |  The [ Snap ] command IS available.<br>
//           |  The [ Start ] command IS available.<br>
//           |  The [ Stop ] command IS available.<br>
//           |  The [ SetRoi ] command IS available.<br>
//           |  The [ SetBinning ] command IS available.<br>
//  FAULT    |  Acquisition/Settings of the detector encounter a problem.<BR>
//           |  The [ Snap ] command IS available.<br>
//           |  The [ Start ] command IS available.<br>
//           |  The [ Stop ] command IS available.<br>
//           |  The [ SetRoi ] command IS available.<br>
//           |  The [ SetBinning ] command IS available.<br>
//  RUNNING  |  The Acquisition is in Progress.<br>
//           |  The [ Snap ] command IS NOT available.<br>
//           |  The [ Start ] command IS NOT available.<br>
//           |  The [ Stop ] command IS available.<br>
//           |  The [ SetRoi ] command IS NOT available.<br>
//           |  The [ SetBinning ] command IS NOT available.<br>


namespace LimaDetector_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_detectorDescription_allowed()
 *	Description : Execution allowed for detectorDescription attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_detectorDescription_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(LimaDetector::detectorDescriptionStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::RUNNING && type==Tango::READ_REQ )
		{
		   return true;
		}
		
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::detectorDescriptionStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_detectorType_allowed()
 *	Description : Execution allowed for detectorType attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_detectorType_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(LimaDetector::detectorTypeStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::RUNNING && type==Tango::READ_REQ )
		{
		   return true;
		}
		
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::detectorTypeStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_detectorModel_allowed()
 *	Description : Execution allowed for detectorModel attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_detectorModel_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(LimaDetector::detectorModelStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::RUNNING && type==Tango::READ_REQ )
		{
		   return true;
		}
		
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::detectorModelStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_detectorWidthMax_allowed()
 *	Description : Execution allowed for detectorWidthMax attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_detectorWidthMax_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(LimaDetector::detectorWidthMaxStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::RUNNING && type==Tango::READ_REQ )
		{
		   return true;
		}
		
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::detectorWidthMaxStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_detectorHeightMax_allowed()
 *	Description : Execution allowed for detectorHeightMax attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_detectorHeightMax_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(LimaDetector::detectorHeightMaxStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::RUNNING && type==Tango::READ_REQ )
		{
		   return true;
		}
		
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::detectorHeightMaxStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_detectorPixelDepth_allowed()
 *	Description : Execution allowed for detectorPixelDepth attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_detectorPixelDepth_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(LimaDetector::detectorPixelDepthStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::RUNNING && type==Tango::READ_REQ )
		{
		   return true;
		}
		
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::detectorPixelDepthStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_binnedWidthMax_allowed()
 *	Description : Execution allowed for binnedWidthMax attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_binnedWidthMax_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(LimaDetector::binnedWidthMaxStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::RUNNING && type==Tango::READ_REQ )
		{
		   return true;
		}
		
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::binnedWidthMaxStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_binnedHeightMax_allowed()
 *	Description : Execution allowed for binnedHeightMax attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_binnedHeightMax_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(LimaDetector::binnedHeightMaxStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::RUNNING && type==Tango::READ_REQ )
		{
		   return true;
		}
		
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::binnedHeightMaxStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_triggerMode_allowed()
 *	Description : Execution allowed for triggerMode attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_triggerMode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for triggerMode attribute in Write access.
	/*----- PROTECTED REGION ID(LimaDetector::triggerModeStateAllowed_WRITE) ENABLED START -----*/
	if (type != Tango::READ_REQ)
	{
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
			if (get_state()==Tango::FAULT && is_device_initialized())
			{
				return true;
			}
			return false;
		}
	}
	/*----- PROTECTED REGION END -----*/	//	LimaDetector::triggerModeStateAllowed_WRITE

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(LimaDetector::triggerModeStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::RUNNING && type==Tango::READ_REQ )
		{
		   return true;
		}
		
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::triggerModeStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_acquisitionMode_allowed()
 *	Description : Execution allowed for acquisitionMode attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_acquisitionMode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for acquisitionMode attribute in Write access.
	/*----- PROTECTED REGION ID(LimaDetector::acquisitionModeStateAllowed_WRITE) ENABLED START -----*/
	if (type != Tango::READ_REQ)
	{
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
			if (get_state()==Tango::FAULT && is_device_initialized())
			{
				return true;
			}
			return false;
		}
	}
	/*----- PROTECTED REGION END -----*/	//	LimaDetector::acquisitionModeStateAllowed_WRITE

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(LimaDetector::acquisitionModeStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::RUNNING && type==Tango::READ_REQ )
		{
		   return true;
		}
		
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::acquisitionModeStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_exposureTime_allowed()
 *	Description : Execution allowed for exposureTime attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_exposureTime_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for exposureTime attribute in Write access.
	/*----- PROTECTED REGION ID(LimaDetector::exposureTimeStateAllowed_WRITE) ENABLED START -----*/
	if (type != Tango::READ_REQ)
	{
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT)
		{
			if (get_state()==Tango::FAULT && is_device_initialized())
			{
				return true;
			}
			return false;
		}
	}
	/*----- PROTECTED REGION END -----*/	//	LimaDetector::exposureTimeStateAllowed_WRITE

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(LimaDetector::exposureTimeStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::exposureTimeStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_latencyTime_allowed()
 *	Description : Execution allowed for latencyTime attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_latencyTime_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for latencyTime attribute in Write access.
	/*----- PROTECTED REGION ID(LimaDetector::latencyTimeStateAllowed_WRITE) ENABLED START -----*/
	if (type != Tango::READ_REQ)
	{
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT)
		{
			if (get_state()==Tango::FAULT && is_device_initialized())
			{
				return true;
			}
			return false;
		}
	}
	/*----- PROTECTED REGION END -----*/	//	LimaDetector::latencyTimeStateAllowed_WRITE

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(LimaDetector::latencyTimeStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::latencyTimeStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_frameRate_allowed()
 *	Description : Execution allowed for frameRate attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_frameRate_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for frameRate attribute in Write access.
	/*----- PROTECTED REGION ID(LimaDetector::frameRateStateAllowed_WRITE) ENABLED START -----*/
	if (type != Tango::READ_REQ)
	{
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT)
		{
			if (get_state()==Tango::FAULT && is_device_initialized())
			{
				return true;
			}
			return false;
		}
	}
	/*----- PROTECTED REGION END -----*/	//	LimaDetector::frameRateStateAllowed_WRITE

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(LimaDetector::frameRateStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::frameRateStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_roiX_allowed()
 *	Description : Execution allowed for roiX attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_roiX_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(LimaDetector::roiXStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::RUNNING && type==Tango::READ_REQ )
		{
		   return true;
		}
		
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::roiXStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_roiY_allowed()
 *	Description : Execution allowed for roiY attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_roiY_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(LimaDetector::roiYStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::RUNNING && type==Tango::READ_REQ )
		{
		   return true;
		}
		
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::roiYStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_roiWidth_allowed()
 *	Description : Execution allowed for roiWidth attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_roiWidth_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(LimaDetector::roiWidthStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::RUNNING && type==Tango::READ_REQ )
		{
		   return true;
		}
		
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::roiWidthStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_roiHeight_allowed()
 *	Description : Execution allowed for roiHeight attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_roiHeight_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(LimaDetector::roiHeightStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::RUNNING && type==Tango::READ_REQ )
		{
		   return true;
		}
		
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::roiHeightStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_binningH_allowed()
 *	Description : Execution allowed for binningH attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_binningH_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(LimaDetector::binningHStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::RUNNING && type==Tango::READ_REQ )
		{
		   return true;
		}
		
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::binningHStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_binningV_allowed()
 *	Description : Execution allowed for binningV attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_binningV_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(LimaDetector::binningVStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::RUNNING && type==Tango::READ_REQ )
		{
		   return true;
		}
		
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::binningVStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_nbFrames_allowed()
 *	Description : Execution allowed for nbFrames attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_nbFrames_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for nbFrames attribute in Write access.
	/*----- PROTECTED REGION ID(LimaDetector::nbFramesStateAllowed_WRITE) ENABLED START -----*/
	if (type != Tango::READ_REQ)
	{
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
			if (get_state()==Tango::FAULT && is_device_initialized())
			{
				return true;
			}
			return false;
		}
	}
	/*----- PROTECTED REGION END -----*/	//	LimaDetector::nbFramesStateAllowed_WRITE

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(LimaDetector::nbFramesStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::RUNNING && type==Tango::READ_REQ )
		{
		   return true;
		}
		
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::nbFramesStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_currentFrame_allowed()
 *	Description : Execution allowed for currentFrame attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_currentFrame_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(LimaDetector::currentFrameStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::RUNNING && type==Tango::READ_REQ )
		{
		   return true;
		}
		
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::currentFrameStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_fileGeneration_allowed()
 *	Description : Execution allowed for fileGeneration attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_fileGeneration_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for fileGeneration attribute in Write access.
	/*----- PROTECTED REGION ID(LimaDetector::fileGenerationStateAllowed_WRITE) ENABLED START -----*/
	if (type != Tango::READ_REQ)
	{
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
			if (get_state()==Tango::FAULT && is_device_initialized())
			{
				return true;
			}
			return false;
		}
	}
	/*----- PROTECTED REGION END -----*/	//	LimaDetector::fileGenerationStateAllowed_WRITE

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(LimaDetector::fileGenerationStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::RUNNING && type==Tango::READ_REQ )
		{
		   return true;
		}
		
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::fileGenerationStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_fileFormat_allowed()
 *	Description : Execution allowed for fileFormat attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_fileFormat_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for fileFormat attribute in Write access.
	/*----- PROTECTED REGION ID(LimaDetector::fileFormatStateAllowed_WRITE) ENABLED START -----*/
	if (type != Tango::READ_REQ)
	{
		if (get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
			if (get_state()==Tango::FAULT && is_device_initialized())
			{
				return true;
			}
			return false;
		}
	}
	/*----- PROTECTED REGION END -----*/	//	LimaDetector::fileFormatStateAllowed_WRITE

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(LimaDetector::fileFormatStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::RUNNING && type==Tango::READ_REQ )
		{
		   return true;
		}
		
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::fileFormatStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_filePrefix_allowed()
 *	Description : Execution allowed for filePrefix attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_filePrefix_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for filePrefix attribute in Write access.
	/*----- PROTECTED REGION ID(LimaDetector::filePrefixStateAllowed_WRITE) ENABLED START -----*/
	if (type != Tango::READ_REQ)
	{
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
			if (get_state()==Tango::FAULT && is_device_initialized())
			{
				return true;
			}
			return false;
		}
	}
	/*----- PROTECTED REGION END -----*/	//	LimaDetector::filePrefixStateAllowed_WRITE

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(LimaDetector::filePrefixStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::RUNNING && type==Tango::READ_REQ )
		{
		   return true;
		}
		
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::filePrefixStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_fileTargetPath_allowed()
 *	Description : Execution allowed for fileTargetPath attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_fileTargetPath_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for fileTargetPath attribute in Write access.
	/*----- PROTECTED REGION ID(LimaDetector::fileTargetPathStateAllowed_WRITE) ENABLED START -----*/
	if (type != Tango::READ_REQ)
	{
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
			if (get_state()==Tango::FAULT && is_device_initialized())
			{
				return true;
			}
			return false;
		}
	}
	/*----- PROTECTED REGION END -----*/	//	LimaDetector::fileTargetPathStateAllowed_WRITE

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(LimaDetector::fileTargetPathStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::RUNNING && type==Tango::READ_REQ )
		{
		   return true;
		}
		
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::fileTargetPathStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_fileNbFrames_allowed()
 *	Description : Execution allowed for fileNbFrames attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_fileNbFrames_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for fileNbFrames attribute in Write access.
	/*----- PROTECTED REGION ID(LimaDetector::fileNbFramesStateAllowed_WRITE) ENABLED START -----*/
	if (type != Tango::READ_REQ)
	{
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
			if (get_state()==Tango::FAULT && is_device_initialized())
			{
				return true;
			}
			return false;
		}
	}
	/*----- PROTECTED REGION END -----*/	//	LimaDetector::fileNbFramesStateAllowed_WRITE

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(LimaDetector::fileNbFramesStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::RUNNING && type==Tango::READ_REQ )
		{
		   return true;
		}
		
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::fileNbFramesStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_fileExtension_allowed()
 *	Description : Execution allowed for fileExtension attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_fileExtension_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(LimaDetector::fileExtensionStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::fileExtensionStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_operationsList_allowed()
 *	Description : Execution allowed for operationsList attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_operationsList_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(LimaDetector::operationsListStateAllowed_READ) ENABLED START -----*/
		if ( get_state()==Tango::RUNNING && type==Tango::READ_REQ )
		{
		   return true;
		}
		
		if ( get_state()==Tango::FAULT && is_device_initialized() )
		{
		   return true;
		}
		/*----- PROTECTED REGION END -----*/	//	LimaDetector::operationsListStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_Prepare_allowed()
 *	Description : Execution allowed for Prepare attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_Prepare_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(LimaDetector::PrepareStateAllowed) ENABLED START -----*/
	if ( get_state()==Tango::FAULT && is_device_initialized() )
	{
	   return true;
	}
	/*----- PROTECTED REGION END -----*/	//	LimaDetector::PrepareStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_Snap_allowed()
 *	Description : Execution allowed for Snap attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_Snap_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(LimaDetector::SnapStateAllowed) ENABLED START -----*/
	if ( get_state()==Tango::FAULT && is_device_initialized() )
	{
	   return true;
	}
	/*----- PROTECTED REGION END -----*/	//	LimaDetector::SnapStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_Start_allowed()
 *	Description : Execution allowed for Start attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_Start_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(LimaDetector::StartStateAllowed) ENABLED START -----*/
	if ( get_state()==Tango::FAULT && is_device_initialized() )
	{
	   return true;
	}
	/*----- PROTECTED REGION END -----*/	//	LimaDetector::StartStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_Stop_allowed()
 *	Description : Execution allowed for Stop attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_Stop_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(LimaDetector::StopStateAllowed) ENABLED START -----*/
	if ( get_state()==Tango::FAULT && is_device_initialized() )
	{
	   return true;
	}
	/*----- PROTECTED REGION END -----*/	//	LimaDetector::StopStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_SetROI_allowed()
 *	Description : Execution allowed for SetROI attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_SetROI_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::FAULT ||
		get_state()==Tango::RUNNING)
	{
	/*----- PROTECTED REGION ID(LimaDetector::SetROIStateAllowed) ENABLED START -----*/
	if ( get_state()==Tango::FAULT && is_device_initialized() )
	{
	   return true;
	}
	/*----- PROTECTED REGION END -----*/	//	LimaDetector::SetROIStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_SetBinning_allowed()
 *	Description : Execution allowed for SetBinning attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_SetBinning_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::FAULT ||
		get_state()==Tango::RUNNING)
	{
	/*----- PROTECTED REGION ID(LimaDetector::SetBinningStateAllowed) ENABLED START -----*/
	if ( get_state()==Tango::FAULT && is_device_initialized() )
	{
	   return true;
	}
	/*----- PROTECTED REGION END -----*/	//	LimaDetector::SetBinningStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_ResetBinning_allowed()
 *	Description : Execution allowed for ResetBinning attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_ResetBinning_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::FAULT ||
		get_state()==Tango::RUNNING)
	{
	/*----- PROTECTED REGION ID(LimaDetector::ResetBinningStateAllowed) ENABLED START -----*/
	if ( get_state()==Tango::FAULT && is_device_initialized() )
	{
	   return true;
	}
	/*----- PROTECTED REGION END -----*/	//	LimaDetector::ResetBinningStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_ResetROI_allowed()
 *	Description : Execution allowed for ResetROI attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_ResetROI_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::FAULT ||
		get_state()==Tango::RUNNING)
	{
	/*----- PROTECTED REGION ID(LimaDetector::ResetROIStateAllowed) ENABLED START -----*/
	if ( get_state()==Tango::FAULT && is_device_initialized() )
	{
	   return true;
	}
	/*----- PROTECTED REGION END -----*/	//	LimaDetector::ResetROIStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_GetAttributeAvailableValues_allowed()
 *	Description : Execution allowed for GetAttributeAvailableValues attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_GetAttributeAvailableValues_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::FAULT ||
		get_state()==Tango::RUNNING)
	{
	/*----- PROTECTED REGION ID(LimaDetector::GetAttributeAvailableValuesStateAllowed) ENABLED START -----*/
	if ( get_state()==Tango::FAULT && is_device_initialized() )
	{
	   return true;
	}
	/*----- PROTECTED REGION END -----*/	//	LimaDetector::GetAttributeAvailableValuesStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_GetAvailableCapabilities_allowed()
 *	Description : Execution allowed for GetAvailableCapabilities attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_GetAvailableCapabilities_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::FAULT ||
		get_state()==Tango::RUNNING)
	{
	/*----- PROTECTED REGION ID(LimaDetector::GetAvailableCapabilitiesStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LimaDetector::GetAvailableCapabilitiesStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_ResetFileIndex_allowed()
 *	Description : Execution allowed for ResetFileIndex attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_ResetFileIndex_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::FAULT ||
		get_state()==Tango::RUNNING)
	{
	/*----- PROTECTED REGION ID(LimaDetector::ResetFileIndexStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LimaDetector::ResetFileIndexStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_ReloadROI_allowed()
 *	Description : Execution allowed for ReloadROI attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_ReloadROI_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::FAULT ||
		get_state()==Tango::RUNNING)
	{
	/*----- PROTECTED REGION ID(LimaDetector::ReloadROIStateAllowed) ENABLED START -----*/
	if ( get_state()==Tango::FAULT && is_device_initialized() )
	{
	   return true;
	}
	/*----- PROTECTED REGION END -----*/	//	LimaDetector::ReloadROIStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_GetDataStreams_allowed()
 *	Description : Execution allowed for GetDataStreams attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_GetDataStreams_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::FAULT ||
		get_state()==Tango::RUNNING)
	{
	/*----- PROTECTED REGION ID(LimaDetector::GetDataStreamsStateAllowed) ENABLED START -----*/
	if ( get_state()==Tango::FAULT && is_device_initialized() )
	{
	   return true;
	}
	/*----- PROTECTED REGION END -----*/	//	LimaDetector::GetDataStreamsStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetector::is_InitInterface_allowed()
 *	Description : Execution allowed for InitInterface attribute
 */
//--------------------------------------------------------
bool LimaDetector::is_InitInterface_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::FAULT ||
		get_state()==Tango::RUNNING)
	{
	/*----- PROTECTED REGION ID(LimaDetector::InitInterfaceStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LimaDetector::InitInterfaceStateAllowed
		return false;
	}
	return true;
}


/*----- PROTECTED REGION ID(LimaDetector::LimaDetectorStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	LimaDetector::LimaDetectorStateAllowed.AdditionalMethods

}	//	End of namespace
