/*----- PROTECTED REGION ID(LimaDetectorClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        LimaDetectorClass.h
//
// description : Include for the LimaDetector root class.
//               This class is the singleton class for
//                the LimaDetector device class.
//               It contains all properties and methods which the 
//               LimaDetector requires only once e.g. the commands.
//
// project :     Lima Device Generic
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef LimaDetectorClass_H
#define LimaDetectorClass_H

#include <tango.h>
#include <LimaDetector.h>


/*----- PROTECTED REGION END -----*/	//	LimaDetectorClass.h


namespace LimaDetector_ns
{
/*----- PROTECTED REGION ID(LimaDetectorClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	LimaDetectorClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute detectorDescription class definition
class detectorDescriptionAttrib: public Tango::Attr
{
public:
	detectorDescriptionAttrib():Attr("detectorDescription",
			Tango::DEV_STRING, Tango::READ) {};
	~detectorDescriptionAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_detectorDescription(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_detectorDescription_allowed(ty);}
};

//	Attribute detectorType class definition
class detectorTypeAttrib: public Tango::Attr
{
public:
	detectorTypeAttrib():Attr("detectorType",
			Tango::DEV_STRING, Tango::READ) {};
	~detectorTypeAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_detectorType(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_detectorType_allowed(ty);}
};

//	Attribute detectorModel class definition
class detectorModelAttrib: public Tango::Attr
{
public:
	detectorModelAttrib():Attr("detectorModel",
			Tango::DEV_STRING, Tango::READ) {};
	~detectorModelAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_detectorModel(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_detectorModel_allowed(ty);}
};

//	Attribute detectorWidthMax class definition
class detectorWidthMaxAttrib: public Tango::Attr
{
public:
	detectorWidthMaxAttrib():Attr("detectorWidthMax",
			Tango::DEV_USHORT, Tango::READ) {};
	~detectorWidthMaxAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_detectorWidthMax(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_detectorWidthMax_allowed(ty);}
};

//	Attribute detectorHeightMax class definition
class detectorHeightMaxAttrib: public Tango::Attr
{
public:
	detectorHeightMaxAttrib():Attr("detectorHeightMax",
			Tango::DEV_USHORT, Tango::READ) {};
	~detectorHeightMaxAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_detectorHeightMax(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_detectorHeightMax_allowed(ty);}
};

//	Attribute detectorPixelDepth class definition
class detectorPixelDepthAttrib: public Tango::Attr
{
public:
	detectorPixelDepthAttrib():Attr("detectorPixelDepth",
			Tango::DEV_USHORT, Tango::READ) {};
	~detectorPixelDepthAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_detectorPixelDepth(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_detectorPixelDepth_allowed(ty);}
};

//	Attribute binnedWidthMax class definition
class binnedWidthMaxAttrib: public Tango::Attr
{
public:
	binnedWidthMaxAttrib():Attr("binnedWidthMax",
			Tango::DEV_USHORT, Tango::READ) {};
	~binnedWidthMaxAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_binnedWidthMax(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_binnedWidthMax_allowed(ty);}
};

//	Attribute binnedHeightMax class definition
class binnedHeightMaxAttrib: public Tango::Attr
{
public:
	binnedHeightMaxAttrib():Attr("binnedHeightMax",
			Tango::DEV_USHORT, Tango::READ) {};
	~binnedHeightMaxAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_binnedHeightMax(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_binnedHeightMax_allowed(ty);}
};

//	Attribute triggerMode class definition
class triggerModeAttrib: public Tango::Attr
{
public:
	triggerModeAttrib():Attr("triggerMode",
			Tango::DEV_STRING, Tango::READ_WRITE) {};
	~triggerModeAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_triggerMode(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<LimaDetector *>(dev))->write_triggerMode(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_triggerMode_allowed(ty);}
};

//	Attribute acquisitionMode class definition
class acquisitionModeAttrib: public Tango::Attr
{
public:
	acquisitionModeAttrib():Attr("acquisitionMode",
			Tango::DEV_STRING, Tango::READ_WRITE) {};
	~acquisitionModeAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_acquisitionMode(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<LimaDetector *>(dev))->write_acquisitionMode(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_acquisitionMode_allowed(ty);}
};

//	Attribute exposureTime class definition
class exposureTimeAttrib: public Tango::Attr
{
public:
	exposureTimeAttrib():Attr("exposureTime",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~exposureTimeAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_exposureTime(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<LimaDetector *>(dev))->write_exposureTime(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_exposureTime_allowed(ty);}
};

//	Attribute latencyTime class definition
class latencyTimeAttrib: public Tango::Attr
{
public:
	latencyTimeAttrib():Attr("latencyTime",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~latencyTimeAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_latencyTime(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<LimaDetector *>(dev))->write_latencyTime(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_latencyTime_allowed(ty);}
};

//	Attribute frameRate class definition
class frameRateAttrib: public Tango::Attr
{
public:
	frameRateAttrib():Attr("frameRate",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~frameRateAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_frameRate(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<LimaDetector *>(dev))->write_frameRate(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_frameRate_allowed(ty);}
};

//	Attribute roiX class definition
class roiXAttrib: public Tango::Attr
{
public:
	roiXAttrib():Attr("roiX",
			Tango::DEV_USHORT, Tango::READ) {};
	~roiXAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_roiX(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_roiX_allowed(ty);}
};

//	Attribute roiY class definition
class roiYAttrib: public Tango::Attr
{
public:
	roiYAttrib():Attr("roiY",
			Tango::DEV_USHORT, Tango::READ) {};
	~roiYAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_roiY(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_roiY_allowed(ty);}
};

//	Attribute roiWidth class definition
class roiWidthAttrib: public Tango::Attr
{
public:
	roiWidthAttrib():Attr("roiWidth",
			Tango::DEV_USHORT, Tango::READ) {};
	~roiWidthAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_roiWidth(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_roiWidth_allowed(ty);}
};

//	Attribute roiHeight class definition
class roiHeightAttrib: public Tango::Attr
{
public:
	roiHeightAttrib():Attr("roiHeight",
			Tango::DEV_USHORT, Tango::READ) {};
	~roiHeightAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_roiHeight(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_roiHeight_allowed(ty);}
};

//	Attribute binningH class definition
class binningHAttrib: public Tango::Attr
{
public:
	binningHAttrib():Attr("binningH",
			Tango::DEV_USHORT, Tango::READ) {};
	~binningHAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_binningH(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_binningH_allowed(ty);}
};

//	Attribute binningV class definition
class binningVAttrib: public Tango::Attr
{
public:
	binningVAttrib():Attr("binningV",
			Tango::DEV_USHORT, Tango::READ) {};
	~binningVAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_binningV(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_binningV_allowed(ty);}
};

//	Attribute nbFrames class definition
class nbFramesAttrib: public Tango::Attr
{
public:
	nbFramesAttrib():Attr("nbFrames",
			Tango::DEV_LONG, Tango::READ_WRITE) {};
	~nbFramesAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_nbFrames(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<LimaDetector *>(dev))->write_nbFrames(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_nbFrames_allowed(ty);}
};

//	Attribute currentFrame class definition
class currentFrameAttrib: public Tango::Attr
{
public:
	currentFrameAttrib():Attr("currentFrame",
			Tango::DEV_ULONG, Tango::READ) {};
	~currentFrameAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_currentFrame(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_currentFrame_allowed(ty);}
};

//	Attribute fileGeneration class definition
class fileGenerationAttrib: public Tango::Attr
{
public:
	fileGenerationAttrib():Attr("fileGeneration",
			Tango::DEV_BOOLEAN, Tango::READ_WRITE) {};
	~fileGenerationAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_fileGeneration(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<LimaDetector *>(dev))->write_fileGeneration(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_fileGeneration_allowed(ty);}
};

//	Attribute fileFormat class definition
class fileFormatAttrib: public Tango::Attr
{
public:
	fileFormatAttrib():Attr("fileFormat",
			Tango::DEV_STRING, Tango::READ_WRITE) {};
	~fileFormatAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_fileFormat(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<LimaDetector *>(dev))->write_fileFormat(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_fileFormat_allowed(ty);}
};

//	Attribute filePrefix class definition
class filePrefixAttrib: public Tango::Attr
{
public:
	filePrefixAttrib():Attr("filePrefix",
			Tango::DEV_STRING, Tango::READ_WRITE) {};
	~filePrefixAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_filePrefix(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<LimaDetector *>(dev))->write_filePrefix(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_filePrefix_allowed(ty);}
};

//	Attribute fileTargetPath class definition
class fileTargetPathAttrib: public Tango::Attr
{
public:
	fileTargetPathAttrib():Attr("fileTargetPath",
			Tango::DEV_STRING, Tango::READ_WRITE) {};
	~fileTargetPathAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_fileTargetPath(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<LimaDetector *>(dev))->write_fileTargetPath(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_fileTargetPath_allowed(ty);}
};

//	Attribute fileNbFrames class definition
class fileNbFramesAttrib: public Tango::Attr
{
public:
	fileNbFramesAttrib():Attr("fileNbFrames",
			Tango::DEV_LONG, Tango::READ_WRITE) {};
	~fileNbFramesAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_fileNbFrames(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<LimaDetector *>(dev))->write_fileNbFrames(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_fileNbFrames_allowed(ty);}
};

//	Attribute fileExtension class definition
class fileExtensionAttrib: public Tango::Attr
{
public:
	fileExtensionAttrib():Attr("fileExtension",
			Tango::DEV_STRING, Tango::READ) {};
	~fileExtensionAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_fileExtension(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_fileExtension_allowed(ty);}
};

//	Attribute operationsList class definition
class operationsListAttrib: public Tango::SpectrumAttr
{
public:
	operationsListAttrib():SpectrumAttr("operationsList",
			Tango::DEV_STRING, Tango::READ, 1024) {};
	~operationsListAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LimaDetector *>(dev))->read_operationsList(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LimaDetector *>(dev))->is_operationsList_allowed(ty);}
};


//=========================================
//	Define classes for commands
//=========================================
//	Command Prepare class definition
class PrepareClass : public Tango::Command
{
public:
	PrepareClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	PrepareClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~PrepareClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<LimaDetector *>(dev))->is_Prepare_allowed(any);}
};

//	Command Snap class definition
class SnapClass : public Tango::Command
{
public:
	SnapClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	SnapClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~SnapClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<LimaDetector *>(dev))->is_Snap_allowed(any);}
};

//	Command Start class definition
class StartClass : public Tango::Command
{
public:
	StartClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	StartClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~StartClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<LimaDetector *>(dev))->is_Start_allowed(any);}
};

//	Command Stop class definition
class StopClass : public Tango::Command
{
public:
	StopClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	StopClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~StopClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<LimaDetector *>(dev))->is_Stop_allowed(any);}
};

//	Command SetROI class definition
class SetROIClass : public Tango::Command
{
public:
	SetROIClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	SetROIClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~SetROIClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<LimaDetector *>(dev))->is_SetROI_allowed(any);}
};

//	Command SetBinning class definition
class SetBinningClass : public Tango::Command
{
public:
	SetBinningClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	SetBinningClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~SetBinningClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<LimaDetector *>(dev))->is_SetBinning_allowed(any);}
};

//	Command ResetBinning class definition
class ResetBinningClass : public Tango::Command
{
public:
	ResetBinningClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	ResetBinningClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~ResetBinningClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<LimaDetector *>(dev))->is_ResetBinning_allowed(any);}
};

//	Command ResetROI class definition
class ResetROIClass : public Tango::Command
{
public:
	ResetROIClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	ResetROIClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~ResetROIClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<LimaDetector *>(dev))->is_ResetROI_allowed(any);}
};

//	Command GetAttributeAvailableValues class definition
class GetAttributeAvailableValuesClass : public Tango::Command
{
public:
	GetAttributeAvailableValuesClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	GetAttributeAvailableValuesClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~GetAttributeAvailableValuesClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<LimaDetector *>(dev))->is_GetAttributeAvailableValues_allowed(any);}
};

//	Command GetAvailableCapabilities class definition
class GetAvailableCapabilitiesClass : public Tango::Command
{
public:
	GetAvailableCapabilitiesClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	GetAvailableCapabilitiesClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~GetAvailableCapabilitiesClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<LimaDetector *>(dev))->is_GetAvailableCapabilities_allowed(any);}
};

//	Command ResetFileIndex class definition
class ResetFileIndexClass : public Tango::Command
{
public:
	ResetFileIndexClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	ResetFileIndexClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~ResetFileIndexClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<LimaDetector *>(dev))->is_ResetFileIndex_allowed(any);}
};

//	Command ReloadROI class definition
class ReloadROIClass : public Tango::Command
{
public:
	ReloadROIClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	ReloadROIClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~ReloadROIClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<LimaDetector *>(dev))->is_ReloadROI_allowed(any);}
};

//	Command GetDataStreams class definition
class GetDataStreamsClass : public Tango::Command
{
public:
	GetDataStreamsClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	GetDataStreamsClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~GetDataStreamsClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<LimaDetector *>(dev))->is_GetDataStreams_allowed(any);}
};

//	Command InitInterface class definition
class InitInterfaceClass : public Tango::Command
{
public:
	InitInterfaceClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	InitInterfaceClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~InitInterfaceClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<LimaDetector *>(dev))->is_InitInterface_allowed(any);}
};


/**
 *	The LimaDetectorClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  LimaDetectorClass : public Tango::DeviceClass
#else
class LimaDetectorClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(LimaDetectorClass::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	LimaDetectorClass::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static LimaDetectorClass *init(const char *);
		static LimaDetectorClass *instance();
		~LimaDetectorClass();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		LimaDetectorClass(string &);
		static LimaDetectorClass *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	LimaDetector_H
